version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - gofmt
    - goimports
    - misspell
    - noctx
    - bodyclose
    - sqlclosecheck
    - exportloopref

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

formatters:
  enable:
    - gofmt
    - goimports
