// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, workspace_id, name, key_hash, key_prefix, role, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, name, key_hash, key_prefix, role, expires_at, created_by, last_used_at, last_ip, last_user_agent, enabled, created_at
`

type CreateAPIKeyParams struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	KeyHash     string             `json:"key_hash"`
	KeyPrefix   string             `json:"key_prefix"`
	Role        string             `json:"role"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedBy   *string            `json:"created_by"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Role,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.LastIp,
		&i.LastUserAgent,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys WHERE id = $1 AND workspace_id = $2
`

type DeleteAPIKeyParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT ak.id, ak.workspace_id, ak.name, ak.key_hash, ak.key_prefix, ak.role, ak.expires_at, ak.created_by, ak.last_used_at, ak.last_ip, ak.last_user_agent, ak.enabled, ak.created_at, w.state AS workspace_state
FROM api_keys ak
JOIN workspaces w ON w.id = ak.workspace_id
WHERE ak.key_hash = $1 AND ak.enabled = true
`

type GetAPIKeyByHashRow struct {
	ID             string             `json:"id"`
	WorkspaceID    string             `json:"workspace_id"`
	Name           string             `json:"name"`
	KeyHash        string             `json:"key_hash"`
	KeyPrefix      string             `json:"key_prefix"`
	Role           string             `json:"role"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedBy      *string            `json:"created_by"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastIp         *string            `json:"last_ip"`
	LastUserAgent  *string            `json:"last_user_agent"`
	Enabled        bool               `json:"enabled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	WorkspaceState string             `json:"workspace_state"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.LastIp,
		&i.LastUserAgent,
		&i.Enabled,
		&i.CreatedAt,
		&i.WorkspaceState,
	)
	return i, err
}

const listAPIKeysByWorkspace = `-- name: ListAPIKeysByWorkspace :many
SELECT id, workspace_id, name, key_hash, key_prefix, role, expires_at, created_by, last_used_at, last_ip, last_user_agent, enabled, created_at FROM api_keys WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByWorkspace(ctx context.Context, workspaceID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Role,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.LastIp,
			&i.LastUserAgent,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyUsage = `-- name: UpdateAPIKeyUsage :exec
UPDATE api_keys SET last_used_at = now(), last_ip = $2, last_user_agent = $3 WHERE id = $1
`

type UpdateAPIKeyUsageParams struct {
	ID            string  `json:"id"`
	LastIp        *string `json:"last_ip"`
	LastUserAgent *string `json:"last_user_agent"`
}

func (q *Queries) UpdateAPIKeyUsage(ctx context.Context, arg UpdateAPIKeyUsageParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyUsage, arg.ID, arg.LastIp, arg.LastUserAgent)
	return err
}
