// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO run_artifacts (id, run_id, workspace_id, name, content_type, size_bytes, storage_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, run_id, workspace_id, name, content_type, size_bytes, storage_key, created_at
`

type CreateArtifactParams struct {
	ID          string  `json:"id"`
	RunID       string  `json:"run_id"`
	WorkspaceID string  `json:"workspace_id"`
	Name        string  `json:"name"`
	ContentType *string `json:"content_type"`
	SizeBytes   *int64  `json:"size_bytes"`
	StorageKey  string  `json:"storage_key"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (RunArtifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ID,
		arg.RunID,
		arg.WorkspaceID,
		arg.Name,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i RunArtifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.WorkspaceID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArtifact = `-- name: DeleteArtifact :execrows
DELETE FROM run_artifacts WHERE run_id = $1 AND name = $2
`

type DeleteArtifactParams struct {
	RunID string `json:"run_id"`
	Name  string `json:"name"`
}

func (q *Queries) DeleteArtifact(ctx context.Context, arg DeleteArtifactParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArtifact, arg.RunID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, run_id, workspace_id, name, content_type, size_bytes, storage_key, created_at FROM run_artifacts WHERE run_id = $1 AND name = $2
`

type GetArtifactParams struct {
	RunID string `json:"run_id"`
	Name  string `json:"name"`
}

func (q *Queries) GetArtifact(ctx context.Context, arg GetArtifactParams) (RunArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, arg.RunID, arg.Name)
	var i RunArtifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.WorkspaceID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsByRun = `-- name: ListArtifactsByRun :many
SELECT id, run_id, name, content_type, size_bytes, created_at
FROM run_artifacts WHERE run_id = $1 ORDER BY created_at
`

type ListArtifactsByRunRow struct {
	ID          string             `json:"id"`
	RunID       string             `json:"run_id"`
	Name        string             `json:"name"`
	ContentType *string            `json:"content_type"`
	SizeBytes   *int64             `json:"size_bytes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListArtifactsByRun(ctx context.Context, runID string) ([]ListArtifactsByRunRow, error) {
	rows, err := q.db.Query(ctx, listArtifactsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactsByRunRow{}
	for rows.Next() {
		var i ListArtifactsByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
