// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
)

const createAuditEntry = `-- name: CreateAuditEntry :one
INSERT INTO audit_log (id, workspace_id, actor_type, actor_id, entity_type, entity_id, action, details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, actor_type, actor_id, entity_type, entity_id, action, details, created_at
`

type CreateAuditEntryParams struct {
	ID          string  `json:"id"`
	WorkspaceID string  `json:"workspace_id"`
	ActorType   string  `json:"actor_type"`
	ActorID     *string `json:"actor_id"`
	EntityType  string  `json:"entity_type"`
	EntityID    string  `json:"entity_id"`
	Action      string  `json:"action"`
	Details     []byte  `json:"details"`
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditEntry,
		arg.ID,
		arg.WorkspaceID,
		arg.ActorType,
		arg.ActorID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Details,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActorType,
		&i.ActorID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditByEntity = `-- name: ListAuditByEntity :many
SELECT id, workspace_id, actor_type, actor_id, entity_type, entity_id, action, details, created_at FROM audit_log
WHERE workspace_id = $1 AND entity_type = $2 AND entity_id = $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAuditByEntityParams struct {
	WorkspaceID string `json:"workspace_id"`
	EntityType  string `json:"entity_type"`
	EntityID    string `json:"entity_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListAuditByEntity(ctx context.Context, arg ListAuditByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByEntity,
		arg.WorkspaceID,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorType,
			&i.ActorID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByWorkspace = `-- name: ListAuditByWorkspace :many
SELECT id, workspace_id, actor_type, actor_id, entity_type, entity_id, action, details, created_at FROM audit_log
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListAuditByWorkspace(ctx context.Context, arg ListAuditByWorkspaceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorType,
			&i.ActorID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
