// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cleanup.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldAudit = `-- name: DeleteOldAudit :execrows
DELETE FROM audit_log
WHERE id IN (
    SELECT a.id FROM audit_log a
    WHERE a.created_at < $1
    LIMIT $2
)
`

type DeleteOldAuditParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) DeleteOldAudit(ctx context.Context, arg DeleteOldAuditParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldAudit, arg.CreatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldJobs = `-- name: DeleteOldJobs :execrows
DELETE FROM jobs
WHERE id IN (
    SELECT j.id FROM jobs j
    WHERE j.state IN ('completed', 'failed', 'killed', 'cancelled')
      AND j.updated_at < $1
    LIMIT $2
)
`

type DeleteOldJobsParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) DeleteOldJobs(ctx context.Context, arg DeleteOldJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldJobs, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldRuns = `-- name: DeleteOldRuns :execrows
DELETE FROM runs
WHERE id IN (
    SELECT r.id FROM runs r
    WHERE r.state IN ('completed', 'failed', 'hung', 'killed', 'skipped', 'cancelled')
      AND r.finished_at < $1
    LIMIT $2
)
`

type DeleteOldRunsParams struct {
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Limit      int32              `json:"limit"`
}

func (q *Queries) DeleteOldRuns(ctx context.Context, arg DeleteOldRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldRuns, arg.FinishedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
