// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createK8sCluster = `-- name: CreateK8sCluster :one
INSERT INTO k8s_clusters (id, workspace_id, name, kubeconfig_enc, default_namespace)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, name, default_namespace, created_at, updated_at
`

type CreateK8sClusterParams struct {
	ID               string  `json:"id"`
	WorkspaceID      string  `json:"workspace_id"`
	Name             string  `json:"name"`
	KubeconfigEnc    []byte  `json:"kubeconfig_enc"`
	DefaultNamespace *string `json:"default_namespace"`
}

type CreateK8sClusterRow struct {
	ID               string             `json:"id"`
	WorkspaceID      string             `json:"workspace_id"`
	Name             string             `json:"name"`
	DefaultNamespace *string            `json:"default_namespace"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// K8s Clusters
func (q *Queries) CreateK8sCluster(ctx context.Context, arg CreateK8sClusterParams) (CreateK8sClusterRow, error) {
	row := q.db.QueryRow(ctx, createK8sCluster,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.KubeconfigEnc,
		arg.DefaultNamespace,
	)
	var i CreateK8sClusterRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.DefaultNamespace,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSSHCredential = `-- name: CreateSSHCredential :one
INSERT INTO ssh_credentials (id, workspace_id, name, private_key_enc, fingerprint, username, port)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, name, fingerprint, username, port, created_at, updated_at
`

type CreateSSHCredentialParams struct {
	ID            string  `json:"id"`
	WorkspaceID   string  `json:"workspace_id"`
	Name          string  `json:"name"`
	PrivateKeyEnc []byte  `json:"private_key_enc"`
	Fingerprint   string  `json:"fingerprint"`
	Username      *string `json:"username"`
	Port          *int32  `json:"port"`
}

type CreateSSHCredentialRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	Fingerprint string             `json:"fingerprint"`
	Username    *string            `json:"username"`
	Port        *int32             `json:"port"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// SSH Credentials
func (q *Queries) CreateSSHCredential(ctx context.Context, arg CreateSSHCredentialParams) (CreateSSHCredentialRow, error) {
	row := q.db.QueryRow(ctx, createSSHCredential,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.PrivateKeyEnc,
		arg.Fingerprint,
		arg.Username,
		arg.Port,
	)
	var i CreateSSHCredentialRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Fingerprint,
		&i.Username,
		&i.Port,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSSMProfile = `-- name: CreateSSMProfile :one
INSERT INTO ssm_profiles (id, workspace_id, name, region, role_arn)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, name, region, role_arn, created_at, updated_at
`

type CreateSSMProfileParams struct {
	ID          string  `json:"id"`
	WorkspaceID string  `json:"workspace_id"`
	Name        string  `json:"name"`
	Region      string  `json:"region"`
	RoleArn     *string `json:"role_arn"`
}

// SSM Profiles
func (q *Queries) CreateSSMProfile(ctx context.Context, arg CreateSSMProfileParams) (SsmProfile, error) {
	row := q.db.QueryRow(ctx, createSSMProfile,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Region,
		arg.RoleArn,
	)
	var i SsmProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Region,
		&i.RoleArn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteK8sCluster = `-- name: DeleteK8sCluster :execrows
DELETE FROM k8s_clusters WHERE id = $1 AND workspace_id = $2
`

type DeleteK8sClusterParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteK8sCluster(ctx context.Context, arg DeleteK8sClusterParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteK8sCluster, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSSHCredential = `-- name: DeleteSSHCredential :execrows
DELETE FROM ssh_credentials WHERE id = $1 AND workspace_id = $2
`

type DeleteSSHCredentialParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteSSHCredential(ctx context.Context, arg DeleteSSHCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSSHCredential, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSSMProfile = `-- name: DeleteSSMProfile :execrows
DELETE FROM ssm_profiles WHERE id = $1 AND workspace_id = $2
`

type DeleteSSMProfileParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteSSMProfile(ctx context.Context, arg DeleteSSMProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSSMProfile, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getK8sCluster = `-- name: GetK8sCluster :one
SELECT id, workspace_id, name, kubeconfig_enc, default_namespace, created_at, updated_at FROM k8s_clusters WHERE id = $1 AND workspace_id = $2
`

type GetK8sClusterParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetK8sCluster(ctx context.Context, arg GetK8sClusterParams) (K8sCluster, error) {
	row := q.db.QueryRow(ctx, getK8sCluster, arg.ID, arg.WorkspaceID)
	var i K8sCluster
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.KubeconfigEnc,
		&i.DefaultNamespace,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSHCredential = `-- name: GetSSHCredential :one
SELECT id, workspace_id, name, private_key_enc, fingerprint, username, port, strict_host_key, created_at, updated_at FROM ssh_credentials WHERE id = $1 AND workspace_id = $2
`

type GetSSHCredentialParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetSSHCredential(ctx context.Context, arg GetSSHCredentialParams) (SshCredential, error) {
	row := q.db.QueryRow(ctx, getSSHCredential, arg.ID, arg.WorkspaceID)
	var i SshCredential
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.PrivateKeyEnc,
		&i.Fingerprint,
		&i.Username,
		&i.Port,
		&i.StrictHostKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSMProfile = `-- name: GetSSMProfile :one
SELECT id, workspace_id, name, region, role_arn, created_at, updated_at FROM ssm_profiles WHERE id = $1 AND workspace_id = $2
`

type GetSSMProfileParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetSSMProfile(ctx context.Context, arg GetSSMProfileParams) (SsmProfile, error) {
	row := q.db.QueryRow(ctx, getSSMProfile, arg.ID, arg.WorkspaceID)
	var i SsmProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Region,
		&i.RoleArn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listK8sClustersByWorkspace = `-- name: ListK8sClustersByWorkspace :many
SELECT id, workspace_id, name, default_namespace, created_at, updated_at
FROM k8s_clusters WHERE workspace_id = $1 ORDER BY name
`

type ListK8sClustersByWorkspaceRow struct {
	ID               string             `json:"id"`
	WorkspaceID      string             `json:"workspace_id"`
	Name             string             `json:"name"`
	DefaultNamespace *string            `json:"default_namespace"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListK8sClustersByWorkspace(ctx context.Context, workspaceID string) ([]ListK8sClustersByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listK8sClustersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListK8sClustersByWorkspaceRow{}
	for rows.Next() {
		var i ListK8sClustersByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.DefaultNamespace,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSHCredentialsByWorkspace = `-- name: ListSSHCredentialsByWorkspace :many
SELECT id, workspace_id, name, fingerprint, username, port, created_at, updated_at
FROM ssh_credentials WHERE workspace_id = $1 ORDER BY name
`

type ListSSHCredentialsByWorkspaceRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	Fingerprint string             `json:"fingerprint"`
	Username    *string            `json:"username"`
	Port        *int32             `json:"port"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSSHCredentialsByWorkspace(ctx context.Context, workspaceID string) ([]ListSSHCredentialsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listSSHCredentialsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSSHCredentialsByWorkspaceRow{}
	for rows.Next() {
		var i ListSSHCredentialsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Fingerprint,
			&i.Username,
			&i.Port,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSMProfilesByWorkspace = `-- name: ListSSMProfilesByWorkspace :many
SELECT id, workspace_id, name, region, role_arn, created_at, updated_at FROM ssm_profiles WHERE workspace_id = $1 ORDER BY name
`

func (q *Queries) ListSSMProfilesByWorkspace(ctx context.Context, workspaceID string) ([]SsmProfile, error) {
	rows, err := q.db.Query(ctx, listSSMProfilesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SsmProfile{}
	for rows.Next() {
		var i SsmProfile
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Region,
			&i.RoleArn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
