// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: heartbeats.sql

package db

import (
	"context"
)

const createHeartbeat = `-- name: CreateHeartbeat :one
INSERT INTO heartbeats (id, run_id, total, current, progress, message)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_id, total, current, progress, message, created_at
`

type CreateHeartbeatParams struct {
	ID       string  `json:"id"`
	RunID    string  `json:"run_id"`
	Total    *int32  `json:"total"`
	Current  *int32  `json:"current"`
	Progress *int32  `json:"progress"`
	Message  *string `json:"message"`
}

func (q *Queries) CreateHeartbeat(ctx context.Context, arg CreateHeartbeatParams) (Heartbeat, error) {
	row := q.db.QueryRow(ctx, createHeartbeat,
		arg.ID,
		arg.RunID,
		arg.Total,
		arg.Current,
		arg.Progress,
		arg.Message,
	)
	var i Heartbeat
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Total,
		&i.Current,
		&i.Progress,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listHeartbeatsByRun = `-- name: ListHeartbeatsByRun :many
SELECT id, run_id, total, current, progress, message, created_at FROM heartbeats WHERE run_id = $1 ORDER BY created_at
`

func (q *Queries) ListHeartbeatsByRun(ctx context.Context, runID string) ([]Heartbeat, error) {
	rows, err := q.db.Query(ctx, listHeartbeatsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Heartbeat{}
	for rows.Next() {
		var i Heartbeat
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Total,
			&i.Current,
			&i.Progress,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
