// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobAttempt = `-- name: CreateJobAttempt :one
INSERT INTO job_attempts (
    id, job_id, attempt_number, started_at, request, worker_id
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, job_id, attempt_number, started_at, finished_at, duration_ms, request, response_code, response_headers, response_body, truncated, original_size, error_message, worker_id, created_at
`

type CreateJobAttemptParams struct {
	ID            string             `json:"id"`
	JobID         string             `json:"job_id"`
	AttemptNumber int32              `json:"attempt_number"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	Request       []byte             `json:"request"`
	WorkerID      *string            `json:"worker_id"`
}

func (q *Queries) CreateJobAttempt(ctx context.Context, arg CreateJobAttemptParams) (JobAttempt, error) {
	row := q.db.QueryRow(ctx, createJobAttempt,
		arg.ID,
		arg.JobID,
		arg.AttemptNumber,
		arg.StartedAt,
		arg.Request,
		arg.WorkerID,
	)
	var i JobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNumber,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Request,
		&i.ResponseCode,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.Truncated,
		&i.OriginalSize,
		&i.ErrorMessage,
		&i.WorkerID,
		&i.CreatedAt,
	)
	return i, err
}

const finishJobAttempt = `-- name: FinishJobAttempt :exec
UPDATE job_attempts SET
    finished_at = $2,
    duration_ms = $3,
    response_code = $4,
    response_headers = $6,
    response_body = $7,
    truncated = $5,
    original_size = $8,
    error_message = $9
WHERE id = $1
`

type FinishJobAttemptParams struct {
	ID              string             `json:"id"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	DurationMs      *int64             `json:"duration_ms"`
	ResponseCode    *int32             `json:"response_code"`
	Truncated       bool               `json:"truncated"`
	ResponseHeaders []byte             `json:"response_headers"`
	ResponseBody    *string            `json:"response_body"`
	OriginalSize    *int64             `json:"original_size"`
	ErrorMessage    *string            `json:"error_message"`
}

func (q *Queries) FinishJobAttempt(ctx context.Context, arg FinishJobAttemptParams) error {
	_, err := q.db.Exec(ctx, finishJobAttempt,
		arg.ID,
		arg.FinishedAt,
		arg.DurationMs,
		arg.ResponseCode,
		arg.Truncated,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.OriginalSize,
		arg.ErrorMessage,
	)
	return err
}

const listJobAttemptsByJob = `-- name: ListJobAttemptsByJob :many
SELECT id, job_id, attempt_number, started_at, finished_at, duration_ms, request, response_code, response_headers, response_body, truncated, original_size, error_message, worker_id, created_at FROM job_attempts WHERE job_id = $1 ORDER BY attempt_number
`

func (q *Queries) ListJobAttemptsByJob(ctx context.Context, jobID string) ([]JobAttempt, error) {
	rows, err := q.db.Query(ctx, listJobAttemptsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobAttempt{}
	for rows.Next() {
		var i JobAttempt
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptNumber,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Request,
			&i.ResponseCode,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.Truncated,
			&i.OriginalSize,
			&i.ErrorMessage,
			&i.WorkerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
