// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendJobAttemptResponseChunk = `-- name: AppendJobAttemptResponseChunk :exec
UPDATE job_attempts
SET response_body = COALESCE(response_body, '') || $2
WHERE id = $1
`

type AppendJobAttemptResponseChunkParams struct {
	ID           string  `json:"id"`
	ResponseBody *string `json:"response_body"`
}

func (q *Queries) AppendJobAttemptResponseChunk(ctx context.Context, arg AppendJobAttemptResponseChunkParams) error {
	_, err := q.db.Exec(ctx, appendJobAttemptResponseChunk, arg.ID, arg.ResponseBody)
	return err
}

const cancelJob = `-- name: CancelJob :exec
UPDATE jobs SET state = 'cancelled', cancel_reason = $2, updated_at = now()
WHERE id = $1
`

type CancelJobParams struct {
	ID           string  `json:"id"`
	CancelReason *string `json:"cancel_reason"`
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) error {
	_, err := q.db.Exec(ctx, cancelJob, arg.ID, arg.CancelReason)
	return err
}

const checkIdempotencyKey = `-- name: CheckIdempotencyKey :one
SELECT id FROM jobs WHERE workspace_id = $1 AND idempotency_key = $2 LIMIT 1
`

type CheckIdempotencyKeyParams struct {
	WorkspaceID    string  `json:"workspace_id"`
	IdempotencyKey *string `json:"idempotency_key"`
}

func (q *Queries) CheckIdempotencyKey(ctx context.Context, arg CheckIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, checkIdempotencyKey, arg.WorkspaceID, arg.IdempotencyKey)
	var id string
	err := row.Scan(&id)
	return id, err
}

const claimPendingJobs = `-- name: ClaimPendingJobs :many
SELECT j.id, j.workspace_id, j.queue_id, j.runtime_override, j.worker_id_override, j.worker_labels_override, j.payload, j.priority, j.max_attempts, j.attempt, j.retry_backoff, j.state, j.scheduled_at, j.expires_at, j.next_attempt_at, j.reference, j.idempotency_key, j.replayed_from_job_id, j.cancel_reason, j.waiting_reason, j.actor_type, j.actor_id, j.effective_config, j.tags, j.worker_id, j.duration_ms, j.created_at, j.updated_at, j.execution_handle, j.stdout_offset, j.stderr_offset, q.execution_method, q.method_config AS queue_method_config,
       q.max_attempts AS queue_max_attempts, q.retry_backoff AS queue_retry_backoff,
       q.job_timeout, q.max_response_size, q.concurrency AS queue_concurrency,
       q.runtime AS queue_runtime, q.worker_id AS queue_worker_id
FROM jobs j
JOIN queues q ON q.id = j.queue_id
JOIN workspaces w ON w.id = j.workspace_id
WHERE (
    (j.state = 'pending' AND j.scheduled_at <= now())
    OR (j.state = 'retrying' AND j.next_attempt_at <= now())
)
AND q.enabled = true
AND w.state = 'active'
ORDER BY j.priority DESC, j.scheduled_at, j.created_at
LIMIT $1
FOR UPDATE OF j SKIP LOCKED
`

type ClaimPendingJobsRow struct {
	ID                   string             `json:"id"`
	WorkspaceID          string             `json:"workspace_id"`
	QueueID              string             `json:"queue_id"`
	RuntimeOverride      *string            `json:"runtime_override"`
	WorkerIDOverride     *string            `json:"worker_id_override"`
	WorkerLabelsOverride []byte             `json:"worker_labels_override"`
	Payload              []byte             `json:"payload"`
	Priority             int32              `json:"priority"`
	MaxAttempts          *int32             `json:"max_attempts"`
	Attempt              int32              `json:"attempt"`
	RetryBackoff         *string            `json:"retry_backoff"`
	State                string             `json:"state"`
	ScheduledAt          pgtype.Timestamptz `json:"scheduled_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	NextAttemptAt        pgtype.Timestamptz `json:"next_attempt_at"`
	Reference            *string            `json:"reference"`
	IdempotencyKey       *string            `json:"idempotency_key"`
	ReplayedFromJobID    *string            `json:"replayed_from_job_id"`
	CancelReason         *string            `json:"cancel_reason"`
	WaitingReason        *string            `json:"waiting_reason"`
	ActorType            *string            `json:"actor_type"`
	ActorID              *string            `json:"actor_id"`
	EffectiveConfig      []byte             `json:"effective_config"`
	Tags                 []string           `json:"tags"`
	WorkerID             *string            `json:"worker_id"`
	DurationMs           *int64             `json:"duration_ms"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ExecutionHandle      []byte             `json:"execution_handle"`
	StdoutOffset         int64              `json:"stdout_offset"`
	StderrOffset         int64              `json:"stderr_offset"`
	ExecutionMethod      string             `json:"execution_method"`
	QueueMethodConfig    []byte             `json:"queue_method_config"`
	QueueMaxAttempts     int32              `json:"queue_max_attempts"`
	QueueRetryBackoff    string             `json:"queue_retry_backoff"`
	JobTimeout           pgtype.Interval    `json:"job_timeout"`
	MaxResponseSize      int32              `json:"max_response_size"`
	QueueConcurrency     int32              `json:"queue_concurrency"`
	QueueRuntime         string             `json:"queue_runtime"`
	QueueWorkerID        *string            `json:"queue_worker_id"`
}

func (q *Queries) ClaimPendingJobs(ctx context.Context, limit int32) ([]ClaimPendingJobsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingJobsRow{}
	for rows.Next() {
		var i ClaimPendingJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.QueueID,
			&i.RuntimeOverride,
			&i.WorkerIDOverride,
			&i.WorkerLabelsOverride,
			&i.Payload,
			&i.Priority,
			&i.MaxAttempts,
			&i.Attempt,
			&i.RetryBackoff,
			&i.State,
			&i.ScheduledAt,
			&i.ExpiresAt,
			&i.NextAttemptAt,
			&i.Reference,
			&i.IdempotencyKey,
			&i.ReplayedFromJobID,
			&i.CancelReason,
			&i.WaitingReason,
			&i.ActorType,
			&i.ActorID,
			&i.EffectiveConfig,
			&i.Tags,
			&i.WorkerID,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExecutionHandle,
			&i.StdoutOffset,
			&i.StderrOffset,
			&i.ExecutionMethod,
			&i.QueueMethodConfig,
			&i.QueueMaxAttempts,
			&i.QueueRetryBackoff,
			&i.JobTimeout,
			&i.MaxResponseSize,
			&i.QueueConcurrency,
			&i.QueueRuntime,
			&i.QueueWorkerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearJobExecutionHandle = `-- name: ClearJobExecutionHandle :exec
UPDATE jobs SET
    execution_handle = NULL,
    stdout_offset = 0,
    stderr_offset = 0,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ClearJobExecutionHandle(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearJobExecutionHandle, id)
	return err
}

const countJobs = `-- name: CountJobs :one
SELECT count(*) FROM jobs
WHERE workspace_id = $1
  AND ($2 = '' OR queue_id = $2)
  AND ($3 = '' OR state = $3)
  AND ($4 = '' OR reference = $4)
`

type CountJobsParams struct {
	WorkspaceID string      `json:"workspace_id"`
	Column2     interface{} `json:"column_2"`
	Column3     interface{} `json:"column_3"`
	Column4     interface{} `json:"column_4"`
}

func (q *Queries) CountJobs(ctx context.Context, arg CountJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunningByQueue = `-- name: CountRunningByQueue :one
SELECT count(*) FROM jobs WHERE queue_id = $1 AND state = 'running'
`

func (q *Queries) CountRunningByQueue(ctx context.Context, queueID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningByQueue, queueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    id, workspace_id, queue_id, payload, priority,
    max_attempts, retry_backoff, scheduled_at, expires_at,
    reference, idempotency_key,
    runtime_override, worker_id_override, worker_labels_override,
    actor_type, actor_id, tags
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11,
    $12, $13, $14,
    $15, $16, $17
)
RETURNING id, workspace_id, queue_id, runtime_override, worker_id_override, worker_labels_override, payload, priority, max_attempts, attempt, retry_backoff, state, scheduled_at, expires_at, next_attempt_at, reference, idempotency_key, replayed_from_job_id, cancel_reason, waiting_reason, actor_type, actor_id, effective_config, tags, worker_id, duration_ms, created_at, updated_at, execution_handle, stdout_offset, stderr_offset
`

type CreateJobParams struct {
	ID                   string             `json:"id"`
	WorkspaceID          string             `json:"workspace_id"`
	QueueID              string             `json:"queue_id"`
	Payload              []byte             `json:"payload"`
	Priority             int32              `json:"priority"`
	MaxAttempts          *int32             `json:"max_attempts"`
	RetryBackoff         *string            `json:"retry_backoff"`
	ScheduledAt          pgtype.Timestamptz `json:"scheduled_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Reference            *string            `json:"reference"`
	IdempotencyKey       *string            `json:"idempotency_key"`
	RuntimeOverride      *string            `json:"runtime_override"`
	WorkerIDOverride     *string            `json:"worker_id_override"`
	WorkerLabelsOverride []byte             `json:"worker_labels_override"`
	ActorType            *string            `json:"actor_type"`
	ActorID              *string            `json:"actor_id"`
	Tags                 []string           `json:"tags"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.WorkspaceID,
		arg.QueueID,
		arg.Payload,
		arg.Priority,
		arg.MaxAttempts,
		arg.RetryBackoff,
		arg.ScheduledAt,
		arg.ExpiresAt,
		arg.Reference,
		arg.IdempotencyKey,
		arg.RuntimeOverride,
		arg.WorkerIDOverride,
		arg.WorkerLabelsOverride,
		arg.ActorType,
		arg.ActorID,
		arg.Tags,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.QueueID,
		&i.RuntimeOverride,
		&i.WorkerIDOverride,
		&i.WorkerLabelsOverride,
		&i.Payload,
		&i.Priority,
		&i.MaxAttempts,
		&i.Attempt,
		&i.RetryBackoff,
		&i.State,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.NextAttemptAt,
		&i.Reference,
		&i.IdempotencyKey,
		&i.ReplayedFromJobID,
		&i.CancelReason,
		&i.WaitingReason,
		&i.ActorType,
		&i.ActorID,
		&i.EffectiveConfig,
		&i.Tags,
		&i.WorkerID,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionHandle,
		&i.StdoutOffset,
		&i.StderrOffset,
	)
	return i, err
}

const createReplayJob = `-- name: CreateReplayJob :one
INSERT INTO jobs (
    id, workspace_id, queue_id, payload, priority,
    max_attempts, retry_backoff, reference, replayed_from_job_id,
    actor_type, actor_id, tags
)
SELECT $2, j.workspace_id, j.queue_id,
    COALESCE($5::jsonb, j.payload),
    COALESCE($6::integer, j.priority),
    j.max_attempts, j.retry_backoff, j.reference, j.id,
    $3, $4, j.tags
FROM jobs j WHERE j.id = $1
RETURNING id, workspace_id, queue_id, runtime_override, worker_id_override, worker_labels_override, payload, priority, max_attempts, attempt, retry_backoff, state, scheduled_at, expires_at, next_attempt_at, reference, idempotency_key, replayed_from_job_id, cancel_reason, waiting_reason, actor_type, actor_id, effective_config, tags, worker_id, duration_ms, created_at, updated_at, execution_handle, stdout_offset, stderr_offset
`

type CreateReplayJobParams struct {
	ID               string  `json:"id"`
	ID_2             string  `json:"id_2"`
	ActorType        *string `json:"actor_type"`
	ActorID          *string `json:"actor_id"`
	OverridePayload  []byte  `json:"override_payload"`
	OverridePriority int32   `json:"override_priority"`
}

func (q *Queries) CreateReplayJob(ctx context.Context, arg CreateReplayJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createReplayJob,
		arg.ID,
		arg.ID_2,
		arg.ActorType,
		arg.ActorID,
		arg.OverridePayload,
		arg.OverridePriority,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.QueueID,
		&i.RuntimeOverride,
		&i.WorkerIDOverride,
		&i.WorkerLabelsOverride,
		&i.Payload,
		&i.Priority,
		&i.MaxAttempts,
		&i.Attempt,
		&i.RetryBackoff,
		&i.State,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.NextAttemptAt,
		&i.Reference,
		&i.IdempotencyKey,
		&i.ReplayedFromJobID,
		&i.CancelReason,
		&i.WaitingReason,
		&i.ActorType,
		&i.ActorID,
		&i.EffectiveConfig,
		&i.Tags,
		&i.WorkerID,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionHandle,
		&i.StdoutOffset,
		&i.StderrOffset,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, workspace_id, queue_id, runtime_override, worker_id_override, worker_labels_override, payload, priority, max_attempts, attempt, retry_backoff, state, scheduled_at, expires_at, next_attempt_at, reference, idempotency_key, replayed_from_job_id, cancel_reason, waiting_reason, actor_type, actor_id, effective_config, tags, worker_id, duration_ms, created_at, updated_at, execution_handle, stdout_offset, stderr_offset FROM jobs WHERE id = $1 AND workspace_id = $2
`

type GetJobParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.WorkspaceID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.QueueID,
		&i.RuntimeOverride,
		&i.WorkerIDOverride,
		&i.WorkerLabelsOverride,
		&i.Payload,
		&i.Priority,
		&i.MaxAttempts,
		&i.Attempt,
		&i.RetryBackoff,
		&i.State,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.NextAttemptAt,
		&i.Reference,
		&i.IdempotencyKey,
		&i.ReplayedFromJobID,
		&i.CancelReason,
		&i.WaitingReason,
		&i.ActorType,
		&i.ActorID,
		&i.EffectiveConfig,
		&i.Tags,
		&i.WorkerID,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionHandle,
		&i.StdoutOffset,
		&i.StderrOffset,
	)
	return i, err
}

const getJobExecutionHandle = `-- name: GetJobExecutionHandle :one
SELECT execution_handle, stdout_offset, stderr_offset
FROM jobs
WHERE id = $1 AND execution_handle IS NOT NULL
`

type GetJobExecutionHandleRow struct {
	ExecutionHandle []byte `json:"execution_handle"`
	StdoutOffset    int64  `json:"stdout_offset"`
	StderrOffset    int64  `json:"stderr_offset"`
}

func (q *Queries) GetJobExecutionHandle(ctx context.Context, id string) (GetJobExecutionHandleRow, error) {
	row := q.db.QueryRow(ctx, getJobExecutionHandle, id)
	var i GetJobExecutionHandleRow
	err := row.Scan(&i.ExecutionHandle, &i.StdoutOffset, &i.StderrOffset)
	return i, err
}

const getJobWithQueue = `-- name: GetJobWithQueue :one
SELECT j.id, j.workspace_id, j.queue_id, j.runtime_override, j.worker_id_override, j.worker_labels_override, j.payload, j.priority, j.max_attempts, j.attempt, j.retry_backoff, j.state, j.scheduled_at, j.expires_at, j.next_attempt_at, j.reference, j.idempotency_key, j.replayed_from_job_id, j.cancel_reason, j.waiting_reason, j.actor_type, j.actor_id, j.effective_config, j.tags, j.worker_id, j.duration_ms, j.created_at, j.updated_at, j.execution_handle, j.stdout_offset, j.stderr_offset, q.name AS queue_name, q.execution_method, q.method_config AS queue_method_config,
       q.max_attempts AS queue_max_attempts, q.retry_backoff AS queue_retry_backoff,
       q.job_timeout, q.max_response_size, q.concurrency AS queue_concurrency
FROM jobs j
JOIN queues q ON q.id = j.queue_id
WHERE j.id = $1 AND j.workspace_id = $2
`

type GetJobWithQueueParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

type GetJobWithQueueRow struct {
	ID                   string             `json:"id"`
	WorkspaceID          string             `json:"workspace_id"`
	QueueID              string             `json:"queue_id"`
	RuntimeOverride      *string            `json:"runtime_override"`
	WorkerIDOverride     *string            `json:"worker_id_override"`
	WorkerLabelsOverride []byte             `json:"worker_labels_override"`
	Payload              []byte             `json:"payload"`
	Priority             int32              `json:"priority"`
	MaxAttempts          *int32             `json:"max_attempts"`
	Attempt              int32              `json:"attempt"`
	RetryBackoff         *string            `json:"retry_backoff"`
	State                string             `json:"state"`
	ScheduledAt          pgtype.Timestamptz `json:"scheduled_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	NextAttemptAt        pgtype.Timestamptz `json:"next_attempt_at"`
	Reference            *string            `json:"reference"`
	IdempotencyKey       *string            `json:"idempotency_key"`
	ReplayedFromJobID    *string            `json:"replayed_from_job_id"`
	CancelReason         *string            `json:"cancel_reason"`
	WaitingReason        *string            `json:"waiting_reason"`
	ActorType            *string            `json:"actor_type"`
	ActorID              *string            `json:"actor_id"`
	EffectiveConfig      []byte             `json:"effective_config"`
	Tags                 []string           `json:"tags"`
	WorkerID             *string            `json:"worker_id"`
	DurationMs           *int64             `json:"duration_ms"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ExecutionHandle      []byte             `json:"execution_handle"`
	StdoutOffset         int64              `json:"stdout_offset"`
	StderrOffset         int64              `json:"stderr_offset"`
	QueueName            string             `json:"queue_name"`
	ExecutionMethod      string             `json:"execution_method"`
	QueueMethodConfig    []byte             `json:"queue_method_config"`
	QueueMaxAttempts     int32              `json:"queue_max_attempts"`
	QueueRetryBackoff    string             `json:"queue_retry_backoff"`
	JobTimeout           pgtype.Interval    `json:"job_timeout"`
	MaxResponseSize      int32              `json:"max_response_size"`
	QueueConcurrency     int32              `json:"queue_concurrency"`
}

func (q *Queries) GetJobWithQueue(ctx context.Context, arg GetJobWithQueueParams) (GetJobWithQueueRow, error) {
	row := q.db.QueryRow(ctx, getJobWithQueue, arg.ID, arg.WorkspaceID)
	var i GetJobWithQueueRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.QueueID,
		&i.RuntimeOverride,
		&i.WorkerIDOverride,
		&i.WorkerLabelsOverride,
		&i.Payload,
		&i.Priority,
		&i.MaxAttempts,
		&i.Attempt,
		&i.RetryBackoff,
		&i.State,
		&i.ScheduledAt,
		&i.ExpiresAt,
		&i.NextAttemptAt,
		&i.Reference,
		&i.IdempotencyKey,
		&i.ReplayedFromJobID,
		&i.CancelReason,
		&i.WaitingReason,
		&i.ActorType,
		&i.ActorID,
		&i.EffectiveConfig,
		&i.Tags,
		&i.WorkerID,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExecutionHandle,
		&i.StdoutOffset,
		&i.StderrOffset,
		&i.QueueName,
		&i.ExecutionMethod,
		&i.QueueMethodConfig,
		&i.QueueMaxAttempts,
		&i.QueueRetryBackoff,
		&i.JobTimeout,
		&i.MaxResponseSize,
		&i.QueueConcurrency,
	)
	return i, err
}

const listActiveAsyncJobs = `-- name: ListActiveAsyncJobs :many
SELECT
    j.id,
    j.workspace_id,
    j.queue_id,
    j.attempt,
    j.state,
    COALESCE(ja.id, '') AS attempt_id,
    ja.started_at,
    j.execution_handle,
    j.stdout_offset,
    j.stderr_offset,
    q.execution_method,
    COALESCE(j.max_attempts, q.max_attempts) AS max_attempts,
    COALESCE(j.retry_backoff, q.retry_backoff) AS retry_backoff,
    q.max_response_size
FROM jobs j
JOIN queues q ON q.id = j.queue_id
LEFT JOIN LATERAL (
    SELECT id, started_at
    FROM job_attempts
    WHERE job_id = j.id AND finished_at IS NULL
    ORDER BY attempt_number DESC
    LIMIT 1
) ja ON true
WHERE j.state IN ('running', 'kill_requested')
  AND j.execution_handle IS NOT NULL
`

type ListActiveAsyncJobsRow struct {
	ID              string             `json:"id"`
	WorkspaceID     string             `json:"workspace_id"`
	QueueID         string             `json:"queue_id"`
	Attempt         int32              `json:"attempt"`
	State           string             `json:"state"`
	AttemptID       string             `json:"attempt_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	ExecutionHandle []byte             `json:"execution_handle"`
	StdoutOffset    int64              `json:"stdout_offset"`
	StderrOffset    int64              `json:"stderr_offset"`
	ExecutionMethod string             `json:"execution_method"`
	MaxAttempts     int32              `json:"max_attempts"`
	RetryBackoff    string             `json:"retry_backoff"`
	MaxResponseSize int32              `json:"max_response_size"`
}

func (q *Queries) ListActiveAsyncJobs(ctx context.Context) ([]ListActiveAsyncJobsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAsyncJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAsyncJobsRow{}
	for rows.Next() {
		var i ListActiveAsyncJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.QueueID,
			&i.Attempt,
			&i.State,
			&i.AttemptID,
			&i.StartedAt,
			&i.ExecutionHandle,
			&i.StdoutOffset,
			&i.StderrOffset,
			&i.ExecutionMethod,
			&i.MaxAttempts,
			&i.RetryBackoff,
			&i.MaxResponseSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingJobs = `-- name: ListExpiredPendingJobs :many
SELECT id, workspace_id, queue_id, runtime_override, worker_id_override, worker_labels_override, payload, priority, max_attempts, attempt, retry_backoff, state, scheduled_at, expires_at, next_attempt_at, reference, idempotency_key, replayed_from_job_id, cancel_reason, waiting_reason, actor_type, actor_id, effective_config, tags, worker_id, duration_ms, created_at, updated_at, execution_handle, stdout_offset, stderr_offset FROM jobs
WHERE state = 'pending' AND expires_at IS NOT NULL AND expires_at <= now()
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListExpiredPendingJobs(ctx context.Context, limit int32) ([]Job, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.QueueID,
			&i.RuntimeOverride,
			&i.WorkerIDOverride,
			&i.WorkerLabelsOverride,
			&i.Payload,
			&i.Priority,
			&i.MaxAttempts,
			&i.Attempt,
			&i.RetryBackoff,
			&i.State,
			&i.ScheduledAt,
			&i.ExpiresAt,
			&i.NextAttemptAt,
			&i.Reference,
			&i.IdempotencyKey,
			&i.ReplayedFromJobID,
			&i.CancelReason,
			&i.WaitingReason,
			&i.ActorType,
			&i.ActorID,
			&i.EffectiveConfig,
			&i.Tags,
			&i.WorkerID,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExecutionHandle,
			&i.StdoutOffset,
			&i.StderrOffset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT j.id, j.workspace_id, j.queue_id, j.runtime_override, j.worker_id_override, j.worker_labels_override, j.payload, j.priority, j.max_attempts, j.attempt, j.retry_backoff, j.state, j.scheduled_at, j.expires_at, j.next_attempt_at, j.reference, j.idempotency_key, j.replayed_from_job_id, j.cancel_reason, j.waiting_reason, j.actor_type, j.actor_id, j.effective_config, j.tags, j.worker_id, j.duration_ms, j.created_at, j.updated_at, j.execution_handle, j.stdout_offset, j.stderr_offset, q.name AS queue_name
FROM jobs j
JOIN queues q ON q.id = j.queue_id
WHERE j.workspace_id = $1
  AND ($2 = '' OR j.queue_id = $2)
  AND ($3 = '' OR j.state = $3)
  AND ($4 = '' OR j.reference = $4)
ORDER BY j.created_at DESC
LIMIT $5 OFFSET $6
`

type ListJobsParams struct {
	WorkspaceID string      `json:"workspace_id"`
	Column2     interface{} `json:"column_2"`
	Column3     interface{} `json:"column_3"`
	Column4     interface{} `json:"column_4"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type ListJobsRow struct {
	ID                   string             `json:"id"`
	WorkspaceID          string             `json:"workspace_id"`
	QueueID              string             `json:"queue_id"`
	RuntimeOverride      *string            `json:"runtime_override"`
	WorkerIDOverride     *string            `json:"worker_id_override"`
	WorkerLabelsOverride []byte             `json:"worker_labels_override"`
	Payload              []byte             `json:"payload"`
	Priority             int32              `json:"priority"`
	MaxAttempts          *int32             `json:"max_attempts"`
	Attempt              int32              `json:"attempt"`
	RetryBackoff         *string            `json:"retry_backoff"`
	State                string             `json:"state"`
	ScheduledAt          pgtype.Timestamptz `json:"scheduled_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	NextAttemptAt        pgtype.Timestamptz `json:"next_attempt_at"`
	Reference            *string            `json:"reference"`
	IdempotencyKey       *string            `json:"idempotency_key"`
	ReplayedFromJobID    *string            `json:"replayed_from_job_id"`
	CancelReason         *string            `json:"cancel_reason"`
	WaitingReason        *string            `json:"waiting_reason"`
	ActorType            *string            `json:"actor_type"`
	ActorID              *string            `json:"actor_id"`
	EffectiveConfig      []byte             `json:"effective_config"`
	Tags                 []string           `json:"tags"`
	WorkerID             *string            `json:"worker_id"`
	DurationMs           *int64             `json:"duration_ms"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ExecutionHandle      []byte             `json:"execution_handle"`
	StdoutOffset         int64              `json:"stdout_offset"`
	StderrOffset         int64              `json:"stderr_offset"`
	QueueName            string             `json:"queue_name"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsRow{}
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.QueueID,
			&i.RuntimeOverride,
			&i.WorkerIDOverride,
			&i.WorkerLabelsOverride,
			&i.Payload,
			&i.Priority,
			&i.MaxAttempts,
			&i.Attempt,
			&i.RetryBackoff,
			&i.State,
			&i.ScheduledAt,
			&i.ExpiresAt,
			&i.NextAttemptAt,
			&i.Reference,
			&i.IdempotencyKey,
			&i.ReplayedFromJobID,
			&i.CancelReason,
			&i.WaitingReason,
			&i.ActorType,
			&i.ActorID,
			&i.EffectiveConfig,
			&i.Tags,
			&i.WorkerID,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExecutionHandle,
			&i.StdoutOffset,
			&i.StderrOffset,
			&i.QueueName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKillRequestedAsyncJobIDs = `-- name: ListKillRequestedAsyncJobIDs :many
SELECT id
FROM jobs
WHERE state = 'kill_requested'
  AND execution_handle IS NOT NULL
`

func (q *Queries) ListKillRequestedAsyncJobIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listKillRequestedAsyncJobIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveJobExecutionHandle = `-- name: SaveJobExecutionHandle :exec
UPDATE jobs SET
    execution_handle = $2,
    stdout_offset = 0,
    stderr_offset = 0,
    updated_at = now()
WHERE id = $1
`

type SaveJobExecutionHandleParams struct {
	ID              string `json:"id"`
	ExecutionHandle []byte `json:"execution_handle"`
}

func (q *Queries) SaveJobExecutionHandle(ctx context.Context, arg SaveJobExecutionHandleParams) error {
	_, err := q.db.Exec(ctx, saveJobExecutionHandle, arg.ID, arg.ExecutionHandle)
	return err
}

const snapshotJobConfig = `-- name: SnapshotJobConfig :exec
UPDATE jobs SET effective_config = $2, updated_at = now() WHERE id = $1
`

type SnapshotJobConfigParams struct {
	ID              string `json:"id"`
	EffectiveConfig []byte `json:"effective_config"`
}

func (q *Queries) SnapshotJobConfig(ctx context.Context, arg SnapshotJobConfigParams) error {
	_, err := q.db.Exec(ctx, snapshotJobConfig, arg.ID, arg.EffectiveConfig)
	return err
}

const updateJobOffsets = `-- name: UpdateJobOffsets :exec
UPDATE jobs SET
    stdout_offset = $2,
    stderr_offset = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateJobOffsetsParams struct {
	ID           string `json:"id"`
	StdoutOffset int64  `json:"stdout_offset"`
	StderrOffset int64  `json:"stderr_offset"`
}

func (q *Queries) UpdateJobOffsets(ctx context.Context, arg UpdateJobOffsetsParams) error {
	_, err := q.db.Exec(ctx, updateJobOffsets, arg.ID, arg.StdoutOffset, arg.StderrOffset)
	return err
}

const updateJobState = `-- name: UpdateJobState :exec
UPDATE jobs SET
    state = $2,
    attempt = COALESCE($3, attempt),
    next_attempt_at = $4,
    cancel_reason = $5,
    waiting_reason = $6,
    worker_id = $7,
    duration_ms = $8,
    updated_at = now()
WHERE id = $1
`

type UpdateJobStateParams struct {
	ID            string             `json:"id"`
	State         string             `json:"state"`
	Attempt       *int32             `json:"attempt"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	CancelReason  *string            `json:"cancel_reason"`
	WaitingReason *string            `json:"waiting_reason"`
	WorkerID      *string            `json:"worker_id"`
	DurationMs    *int64             `json:"duration_ms"`
}

func (q *Queries) UpdateJobState(ctx context.Context, arg UpdateJobStateParams) error {
	_, err := q.db.Exec(ctx, updateJobState,
		arg.ID,
		arg.State,
		arg.Attempt,
		arg.NextAttemptAt,
		arg.CancelReason,
		arg.WaitingReason,
		arg.WorkerID,
		arg.DurationMs,
	)
	return err
}
