// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM workspace_memberships
WHERE workspace_id = $1 AND role = 'admin'
`

func (q *Queries) CountAdmins(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO workspace_memberships (id, workspace_id, user_id, role)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, user_id, role, created_at, updated_at
`

type CreateMembershipParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	Role        string `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
	)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE FROM workspace_memberships WHERE workspace_id = $1 AND user_id = $2
`

type DeleteMembershipParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembership, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMembership = `-- name: GetMembership :one
SELECT id, workspace_id, user_id, role, created_at, updated_at FROM workspace_memberships
WHERE workspace_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT wm.id, wm.workspace_id, wm.user_id, wm.role, wm.created_at, wm.updated_at, w.name AS workspace_name, w.slug AS workspace_slug
FROM workspace_memberships wm
JOIN workspaces w ON w.id = wm.workspace_id
WHERE wm.user_id = $1
ORDER BY wm.created_at
`

type ListMembershipsByUserRow struct {
	ID            string             `json:"id"`
	WorkspaceID   string             `json:"workspace_id"`
	UserID        string             `json:"user_id"`
	Role          string             `json:"role"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	WorkspaceName string             `json:"workspace_name"`
	WorkspaceSlug string             `json:"workspace_slug"`
}

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID string) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByUserRow{}
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceName,
			&i.WorkspaceSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByWorkspace = `-- name: ListMembershipsByWorkspace :many
SELECT wm.id, wm.workspace_id, wm.user_id, wm.role, wm.created_at, wm.updated_at, u.email, u.name AS user_name
FROM workspace_memberships wm
JOIN users u ON u.id = wm.user_id
WHERE wm.workspace_id = $1
ORDER BY wm.created_at
`

type ListMembershipsByWorkspaceRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	UserID      string             `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Email       string             `json:"email"`
	UserName    string             `json:"user_name"`
}

func (q *Queries) ListMembershipsByWorkspace(ctx context.Context, workspaceID string) ([]ListMembershipsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByWorkspaceRow{}
	for rows.Next() {
		var i ListMembershipsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE workspace_memberships SET role = $3, updated_at = now()
WHERE workspace_id = $1 AND user_id = $2
RETURNING id, workspace_id, user_id, role, created_at, updated_at
`

type UpdateMembershipRoleParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	Role        string `json:"role"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
