// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID            string             `json:"id"`
	WorkspaceID   string             `json:"workspace_id"`
	Name          string             `json:"name"`
	KeyHash       string             `json:"key_hash"`
	KeyPrefix     string             `json:"key_prefix"`
	Role          string             `json:"role"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedBy     *string            `json:"created_by"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	LastIp        *string            `json:"last_ip"`
	LastUserAgent *string            `json:"last_user_agent"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	ActorType   string             `json:"actor_type"`
	ActorID     *string            `json:"actor_id"`
	EntityType  string             `json:"entity_type"`
	EntityID    string             `json:"entity_id"`
	Action      string             `json:"action"`
	Details     []byte             `json:"details"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Heartbeat struct {
	ID        string             `json:"id"`
	RunID     string             `json:"run_id"`
	Total     *int32             `json:"total"`
	Current   *int32             `json:"current"`
	Progress  *int32             `json:"progress"`
	Message   *string            `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID                   string             `json:"id"`
	WorkspaceID          string             `json:"workspace_id"`
	QueueID              string             `json:"queue_id"`
	RuntimeOverride      *string            `json:"runtime_override"`
	WorkerIDOverride     *string            `json:"worker_id_override"`
	WorkerLabelsOverride []byte             `json:"worker_labels_override"`
	Payload              []byte             `json:"payload"`
	Priority             int32              `json:"priority"`
	MaxAttempts          *int32             `json:"max_attempts"`
	Attempt              int32              `json:"attempt"`
	RetryBackoff         *string            `json:"retry_backoff"`
	State                string             `json:"state"`
	ScheduledAt          pgtype.Timestamptz `json:"scheduled_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	NextAttemptAt        pgtype.Timestamptz `json:"next_attempt_at"`
	Reference            *string            `json:"reference"`
	IdempotencyKey       *string            `json:"idempotency_key"`
	ReplayedFromJobID    *string            `json:"replayed_from_job_id"`
	CancelReason         *string            `json:"cancel_reason"`
	WaitingReason        *string            `json:"waiting_reason"`
	ActorType            *string            `json:"actor_type"`
	ActorID              *string            `json:"actor_id"`
	EffectiveConfig      []byte             `json:"effective_config"`
	Tags                 []string           `json:"tags"`
	WorkerID             *string            `json:"worker_id"`
	DurationMs           *int64             `json:"duration_ms"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type JobAttempt struct {
	ID              string             `json:"id"`
	JobID           string             `json:"job_id"`
	AttemptNumber   int32              `json:"attempt_number"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	DurationMs      *int64             `json:"duration_ms"`
	Request         []byte             `json:"request"`
	ResponseCode    *int32             `json:"response_code"`
	ResponseHeaders []byte             `json:"response_headers"`
	ResponseBody    *string            `json:"response_body"`
	Truncated       bool               `json:"truncated"`
	OriginalSize    *int64             `json:"original_size"`
	ErrorMessage    *string            `json:"error_message"`
	WorkerID        *string            `json:"worker_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type K8sCluster struct {
	ID               string             `json:"id"`
	WorkspaceID      string             `json:"workspace_id"`
	Name             string             `json:"name"`
	KubeconfigEnc    []byte             `json:"kubeconfig_enc"`
	DefaultNamespace *string            `json:"default_namespace"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Process struct {
	ID                 string             `json:"id"`
	WorkspaceID        string             `json:"workspace_id"`
	Name               string             `json:"name"`
	ScheduleType       string             `json:"schedule_type"`
	Schedule           *string            `json:"schedule"`
	DelayDuration      *string            `json:"delay_duration"`
	Timezone           *string            `json:"timezone"`
	MissPolicy         *string            `json:"miss_policy"`
	MaxRecoverySlots   int32              `json:"max_recovery_slots"`
	AllowParallel      bool               `json:"allow_parallel"`
	MaxParallel        int32              `json:"max_parallel"`
	OnOverlap          string             `json:"on_overlap"`
	ExecutionMethod    string             `json:"execution_method"`
	Runtime            string             `json:"runtime"`
	MethodConfig       []byte             `json:"method_config"`
	MaxAttempts        int32              `json:"max_attempts"`
	RetryBackoff       *string            `json:"retry_backoff"`
	ExecutionTimeout   pgtype.Interval    `json:"execution_timeout"`
	HeartbeatTimeout   pgtype.Interval    `json:"heartbeat_timeout"`
	TimeoutAction      string             `json:"timeout_action"`
	SshCredentialID    *string            `json:"ssh_credential_id"`
	SsmProfileID       *string            `json:"ssm_profile_id"`
	K8sClusterID       *string            `json:"k8s_cluster_id"`
	WorkerID           *string            `json:"worker_id"`
	WorkerLabels       []byte             `json:"worker_labels"`
	DependsOnProcessID *string            `json:"depends_on_process_id"`
	DependencyType     *string            `json:"dependency_type"`
	Environment        []byte             `json:"environment"`
	Tags               []string           `json:"tags"`
	Enabled            bool               `json:"enabled"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Queue struct {
	ID              string             `json:"id"`
	WorkspaceID     string             `json:"workspace_id"`
	Name            string             `json:"name"`
	ExecutionMethod string             `json:"execution_method"`
	Runtime         string             `json:"runtime"`
	MethodConfig    []byte             `json:"method_config"`
	Concurrency     int32              `json:"concurrency"`
	MaxAttempts     int32              `json:"max_attempts"`
	RetryBackoff    string             `json:"retry_backoff"`
	JobTimeout      pgtype.Interval    `json:"job_timeout"`
	MaxResponseSize int32              `json:"max_response_size"`
	SshCredentialID *string            `json:"ssh_credential_id"`
	SsmProfileID    *string            `json:"ssm_profile_id"`
	K8sClusterID    *string            `json:"k8s_cluster_id"`
	WorkerID        *string            `json:"worker_id"`
	WorkerLabels    []byte             `json:"worker_labels"`
	Tags            []string           `json:"tags"`
	Enabled         bool               `json:"enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Run struct {
	ID                string             `json:"id"`
	WorkspaceID       string             `json:"workspace_id"`
	ProcessID         string             `json:"process_id"`
	ScheduledAt       pgtype.Timestamptz `json:"scheduled_at"`
	State             string             `json:"state"`
	Origin            string             `json:"origin"`
	Attempt           int32              `json:"attempt"`
	MaxAttempts       int32              `json:"max_attempts"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	DurationMs        *int64             `json:"duration_ms"`
	ExitCode          *int32             `json:"exit_code"`
	ProgressTotal     *int32             `json:"progress_total"`
	ProgressCurrent   *int32             `json:"progress_current"`
	Progress          *int32             `json:"progress"`
	ProgressMessage   *string            `json:"progress_message"`
	LastHeartbeatAt   pgtype.Timestamptz `json:"last_heartbeat_at"`
	QueueReason       *string            `json:"queue_reason"`
	WaitingReason     *string            `json:"waiting_reason"`
	ActorType         *string            `json:"actor_type"`
	ActorID           *string            `json:"actor_id"`
	KilledByActorType *string            `json:"killed_by_actor_type"`
	KilledByActorID   *string            `json:"killed_by_actor_id"`
	TriggeredByRunID  *string            `json:"triggered_by_run_id"`
	ReplayedFromRunID *string            `json:"replayed_from_run_id"`
	EffectiveConfig   []byte             `json:"effective_config"`
	Runtime           *string            `json:"runtime"`
	WorkerID          *string            `json:"worker_id"`
	Tags              []string           `json:"tags"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RunAttempt struct {
	ID            string             `json:"id"`
	RunID         string             `json:"run_id"`
	AttemptNumber int32              `json:"attempt_number"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	DurationMs    *int64             `json:"duration_ms"`
	ExitCode      *int32             `json:"exit_code"`
	WorkerID      *string            `json:"worker_id"`
	ErrorMessage  *string            `json:"error_message"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RunOutput struct {
	ID        string             `json:"id"`
	RunID     string             `json:"run_id"`
	Stream    string             `json:"stream"`
	Content   string             `json:"content"`
	Truncated bool               `json:"truncated"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SshCredential struct {
	ID            string             `json:"id"`
	WorkspaceID   string             `json:"workspace_id"`
	Name          string             `json:"name"`
	PrivateKeyEnc []byte             `json:"private_key_enc"`
	Fingerprint   string             `json:"fingerprint"`
	Username      *string            `json:"username"`
	Port          *int32             `json:"port"`
	StrictHostKey bool               `json:"strict_host_key"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SsmProfile struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	Region      string             `json:"region"`
	RoleArn     *string            `json:"role_arn"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                string             `json:"id"`
	Email             string             `json:"email"`
	Name              string             `json:"name"`
	AuthProvider      string             `json:"auth_provider"`
	PasswordHash      *string            `json:"password_hash"`
	EmailVerified     bool               `json:"email_verified"`
	IsPlatformAdmin   bool               `json:"is_platform_admin"`
	ActiveWorkspaceID *string            `json:"active_workspace_id"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type WebhookSubscription struct {
	ID                  string             `json:"id"`
	WorkspaceID         string             `json:"workspace_id"`
	Url                 string             `json:"url"`
	Secret              string             `json:"secret"`
	EventTypes          []string           `json:"event_types"`
	Enabled             bool               `json:"enabled"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	AutoDisabled        bool               `json:"auto_disabled"`
	LastDeliveryAt      pgtype.Timestamptz `json:"last_delivery_at"`
	LastFailureAt       pgtype.Timestamptz `json:"last_failure_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Worker struct {
	ID                       string             `json:"id"`
	WorkspaceID              string             `json:"workspace_id"`
	Name                     string             `json:"name"`
	CredentialHash           string             `json:"credential_hash"`
	Labels                   []byte             `json:"labels"`
	Capabilities             []byte             `json:"capabilities"`
	MaxConcurrency           int32              `json:"max_concurrency"`
	Version                  *string            `json:"version"`
	Enabled                  bool               `json:"enabled"`
	Status                   string             `json:"status"`
	LastHeartbeatAt          pgtype.Timestamptz `json:"last_heartbeat_at"`
	ConsecutiveFailures      int32              `json:"consecutive_failures"`
	ConsecutiveHealthy       int32              `json:"consecutive_healthy"`
	EnrollmentTokenHash      *string            `json:"enrollment_token_hash"`
	EnrollmentTokenExpiresAt pgtype.Timestamptz `json:"enrollment_token_expires_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID              string             `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	State           string             `json:"state"`
	DefaultTimezone string             `json:"default_timezone"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceMembership struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	UserID      string             `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
