// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orchestras.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrchestra = `-- name: CreateOrchestra :one
INSERT INTO orchestras (id, workspace_id, name, director_type, director_process_id, ai_config, secrets, budget, timeout, timeout_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, workspace_id, name, director_type, director_process_id, ai_config, state, movement_count, secrets, summary, budget, budget_used, timeout, timeout_at, created_at, updated_at
`

type CreateOrchestraParams struct {
	ID                string             `json:"id"`
	WorkspaceID       string             `json:"workspace_id"`
	Name              string             `json:"name"`
	DirectorType      string             `json:"director_type"`
	DirectorProcessID *string            `json:"director_process_id"`
	AiConfig          []byte             `json:"ai_config"`
	Secrets           []string           `json:"secrets"`
	Budget            []byte             `json:"budget"`
	Timeout           pgtype.Interval    `json:"timeout"`
	TimeoutAt         pgtype.Timestamptz `json:"timeout_at"`
}

func (q *Queries) CreateOrchestra(ctx context.Context, arg CreateOrchestraParams) (Orchestra, error) {
	row := q.db.QueryRow(ctx, createOrchestra,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.DirectorType,
		arg.DirectorProcessID,
		arg.AiConfig,
		arg.Secrets,
		arg.Budget,
		arg.Timeout,
		arg.TimeoutAt,
	)
	var i Orchestra
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.DirectorType,
		&i.DirectorProcessID,
		&i.AiConfig,
		&i.State,
		&i.MovementCount,
		&i.Secrets,
		&i.Summary,
		&i.Budget,
		&i.BudgetUsed,
		&i.Timeout,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishOrchestra = `-- name: FinishOrchestra :exec
UPDATE orchestras SET state = 'completed', summary = $2, updated_at = now() WHERE id = $1
`

type FinishOrchestraParams struct {
	ID      string  `json:"id"`
	Summary *string `json:"summary"`
}

func (q *Queries) FinishOrchestra(ctx context.Context, arg FinishOrchestraParams) error {
	_, err := q.db.Exec(ctx, finishOrchestra, arg.ID, arg.Summary)
	return err
}

const getOrchestra = `-- name: GetOrchestra :one
SELECT id, workspace_id, name, director_type, director_process_id, ai_config, state, movement_count, secrets, summary, budget, budget_used, timeout, timeout_at, created_at, updated_at FROM orchestras WHERE id = $1 AND workspace_id = $2
`

type GetOrchestraParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetOrchestra(ctx context.Context, arg GetOrchestraParams) (Orchestra, error) {
	row := q.db.QueryRow(ctx, getOrchestra, arg.ID, arg.WorkspaceID)
	var i Orchestra
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.DirectorType,
		&i.DirectorProcessID,
		&i.AiConfig,
		&i.State,
		&i.MovementCount,
		&i.Secrets,
		&i.Summary,
		&i.Budget,
		&i.BudgetUsed,
		&i.Timeout,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementMovementCount = `-- name: IncrementMovementCount :exec
UPDATE orchestras SET movement_count = movement_count + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) IncrementMovementCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementMovementCount, id)
	return err
}

const listMovementsByOrchestra = `-- name: ListMovementsByOrchestra :many
SELECT id, workspace_id, process_id, scheduled_at, state, origin, attempt, max_attempts, next_attempt_at, started_at, finished_at, duration_ms, exit_code, progress_total, progress_current, progress, progress_message, last_heartbeat_at, queue_reason, waiting_reason, actor_type, actor_id, killed_by_actor_type, killed_by_actor_id, triggered_by_run_id, replayed_from_run_id, effective_config, runtime, worker_id, tags, created_at, updated_at, result, orchestra_id, orchestra_step, choice_config, chosen_index, execution_handle, stdout_offset, stderr_offset FROM runs WHERE orchestra_id = $1 ORDER BY orchestra_step
`

func (q *Queries) ListMovementsByOrchestra(ctx context.Context, orchestraID *string) ([]Run, error) {
	rows, err := q.db.Query(ctx, listMovementsByOrchestra, orchestraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProcessID,
			&i.ScheduledAt,
			&i.State,
			&i.Origin,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ExitCode,
			&i.ProgressTotal,
			&i.ProgressCurrent,
			&i.Progress,
			&i.ProgressMessage,
			&i.LastHeartbeatAt,
			&i.QueueReason,
			&i.WaitingReason,
			&i.ActorType,
			&i.ActorID,
			&i.KilledByActorType,
			&i.KilledByActorID,
			&i.TriggeredByRunID,
			&i.ReplayedFromRunID,
			&i.EffectiveConfig,
			&i.Runtime,
			&i.WorkerID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Result,
			&i.OrchestraID,
			&i.OrchestraStep,
			&i.ChoiceConfig,
			&i.ChosenIndex,
			&i.ExecutionHandle,
			&i.StdoutOffset,
			&i.StderrOffset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrchestrasByWorkspace = `-- name: ListOrchestrasByWorkspace :many
SELECT id, workspace_id, name, director_type, director_process_id, ai_config, state, movement_count, secrets, summary, budget, budget_used, timeout, timeout_at, created_at, updated_at FROM orchestras WHERE workspace_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListOrchestrasByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListOrchestrasByWorkspace(ctx context.Context, arg ListOrchestrasByWorkspaceParams) ([]Orchestra, error) {
	rows, err := q.db.Query(ctx, listOrchestrasByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Orchestra{}
	for rows.Next() {
		var i Orchestra
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.DirectorType,
			&i.DirectorProcessID,
			&i.AiConfig,
			&i.State,
			&i.MovementCount,
			&i.Secrets,
			&i.Summary,
			&i.Budget,
			&i.BudgetUsed,
			&i.Timeout,
			&i.TimeoutAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrchestraBudgetUsed = `-- name: UpdateOrchestraBudgetUsed :exec
UPDATE orchestras SET budget_used = $2, updated_at = now() WHERE id = $1
`

type UpdateOrchestraBudgetUsedParams struct {
	ID         string `json:"id"`
	BudgetUsed []byte `json:"budget_used"`
}

func (q *Queries) UpdateOrchestraBudgetUsed(ctx context.Context, arg UpdateOrchestraBudgetUsedParams) error {
	_, err := q.db.Exec(ctx, updateOrchestraBudgetUsed, arg.ID, arg.BudgetUsed)
	return err
}

const updateOrchestraState = `-- name: UpdateOrchestraState :exec
UPDATE orchestras SET state = $2, updated_at = now() WHERE id = $1
`

type UpdateOrchestraStateParams struct {
	ID    string `json:"id"`
	State string `json:"state"`
}

func (q *Queries) UpdateOrchestraState(ctx context.Context, arg UpdateOrchestraStateParams) error {
	_, err := q.db.Exec(ctx, updateOrchestraState, arg.ID, arg.State)
	return err
}
