// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orchestra_chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO orchestra_chat (id, orchestra_id, sender_type, sender_id, message_type, content, data)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, orchestra_id, sender_type, sender_id, message_type, content, data, created_at
`

type CreateChatMessageParams struct {
	ID          string  `json:"id"`
	OrchestraID string  `json:"orchestra_id"`
	SenderType  string  `json:"sender_type"`
	SenderID    *string `json:"sender_id"`
	MessageType string  `json:"message_type"`
	Content     string  `json:"content"`
	Data        []byte  `json:"data"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (OrchestraChat, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.ID,
		arg.OrchestraID,
		arg.SenderType,
		arg.SenderID,
		arg.MessageType,
		arg.Content,
		arg.Data,
	)
	var i OrchestraChat
	err := row.Scan(
		&i.ID,
		&i.OrchestraID,
		&i.SenderType,
		&i.SenderID,
		&i.MessageType,
		&i.Content,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, orchestra_id, sender_type, sender_id, message_type, content, data, created_at FROM orchestra_chat
WHERE orchestra_id = $1 AND created_at > $2
ORDER BY created_at
LIMIT $3
`

type ListChatMessagesParams struct {
	OrchestraID string             `json:"orchestra_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]OrchestraChat, error) {
	rows, err := q.db.Query(ctx, listChatMessages, arg.OrchestraID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrchestraChat{}
	for rows.Next() {
		var i OrchestraChat
		if err := rows.Scan(
			&i.ID,
			&i.OrchestraID,
			&i.SenderType,
			&i.SenderID,
			&i.MessageType,
			&i.Content,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessagesAll = `-- name: ListChatMessagesAll :many
SELECT id, orchestra_id, sender_type, sender_id, message_type, content, data, created_at FROM orchestra_chat
WHERE orchestra_id = $1
ORDER BY created_at
LIMIT $2 OFFSET $3
`

type ListChatMessagesAllParams struct {
	OrchestraID string `json:"orchestra_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListChatMessagesAll(ctx context.Context, arg ListChatMessagesAllParams) ([]OrchestraChat, error) {
	rows, err := q.db.Query(ctx, listChatMessagesAll, arg.OrchestraID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrchestraChat{}
	for rows.Next() {
		var i OrchestraChat
		if err := rows.Scan(
			&i.ID,
			&i.OrchestraID,
			&i.SenderType,
			&i.SenderID,
			&i.MessageType,
			&i.Content,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
