// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProcesses = `-- name: CountProcesses :one
SELECT count(*) FROM processes WHERE workspace_id = $1
`

func (q *Queries) CountProcesses(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProcesses, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProcess = `-- name: CreateProcess :one
INSERT INTO processes (
    id, workspace_id, name, schedule_type, schedule, delay_duration, timezone,
    miss_policy, max_recovery_slots, allow_parallel, max_parallel, on_overlap,
    execution_method, runtime, method_config,
    max_attempts, retry_backoff, execution_timeout, heartbeat_timeout, timeout_action,
    ssh_credential_id, ssm_profile_id, k8s_cluster_id,
    worker_id, worker_labels,
    depends_on_process_id, dependency_type,
    environment, tags, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15,
    $16, $17, $18, $19, $20,
    $21, $22, $23,
    $24, $25,
    $26, $27,
    $28, $29, $30
)
RETURNING id, workspace_id, name, schedule_type, schedule, delay_duration, timezone, miss_policy, max_recovery_slots, allow_parallel, max_parallel, on_overlap, execution_method, runtime, method_config, max_attempts, retry_backoff, execution_timeout, heartbeat_timeout, timeout_action, ssh_credential_id, ssm_profile_id, k8s_cluster_id, worker_id, worker_labels, depends_on_process_id, dependency_type, environment, tags, enabled, created_at, updated_at
`

type CreateProcessParams struct {
	ID                 string          `json:"id"`
	WorkspaceID        string          `json:"workspace_id"`
	Name               string          `json:"name"`
	ScheduleType       string          `json:"schedule_type"`
	Schedule           *string         `json:"schedule"`
	DelayDuration      *string         `json:"delay_duration"`
	Timezone           *string         `json:"timezone"`
	MissPolicy         *string         `json:"miss_policy"`
	MaxRecoverySlots   int32           `json:"max_recovery_slots"`
	AllowParallel      bool            `json:"allow_parallel"`
	MaxParallel        int32           `json:"max_parallel"`
	OnOverlap          string          `json:"on_overlap"`
	ExecutionMethod    string          `json:"execution_method"`
	Runtime            string          `json:"runtime"`
	MethodConfig       []byte          `json:"method_config"`
	MaxAttempts        int32           `json:"max_attempts"`
	RetryBackoff       *string         `json:"retry_backoff"`
	ExecutionTimeout   pgtype.Interval `json:"execution_timeout"`
	HeartbeatTimeout   pgtype.Interval `json:"heartbeat_timeout"`
	TimeoutAction      string          `json:"timeout_action"`
	SshCredentialID    *string         `json:"ssh_credential_id"`
	SsmProfileID       *string         `json:"ssm_profile_id"`
	K8sClusterID       *string         `json:"k8s_cluster_id"`
	WorkerID           *string         `json:"worker_id"`
	WorkerLabels       []byte          `json:"worker_labels"`
	DependsOnProcessID *string         `json:"depends_on_process_id"`
	DependencyType     *string         `json:"dependency_type"`
	Environment        []byte          `json:"environment"`
	Tags               []string        `json:"tags"`
	Enabled            bool            `json:"enabled"`
}

func (q *Queries) CreateProcess(ctx context.Context, arg CreateProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, createProcess,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ScheduleType,
		arg.Schedule,
		arg.DelayDuration,
		arg.Timezone,
		arg.MissPolicy,
		arg.MaxRecoverySlots,
		arg.AllowParallel,
		arg.MaxParallel,
		arg.OnOverlap,
		arg.ExecutionMethod,
		arg.Runtime,
		arg.MethodConfig,
		arg.MaxAttempts,
		arg.RetryBackoff,
		arg.ExecutionTimeout,
		arg.HeartbeatTimeout,
		arg.TimeoutAction,
		arg.SshCredentialID,
		arg.SsmProfileID,
		arg.K8sClusterID,
		arg.WorkerID,
		arg.WorkerLabels,
		arg.DependsOnProcessID,
		arg.DependencyType,
		arg.Environment,
		arg.Tags,
		arg.Enabled,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ScheduleType,
		&i.Schedule,
		&i.DelayDuration,
		&i.Timezone,
		&i.MissPolicy,
		&i.MaxRecoverySlots,
		&i.AllowParallel,
		&i.MaxParallel,
		&i.OnOverlap,
		&i.ExecutionMethod,
		&i.Runtime,
		&i.MethodConfig,
		&i.MaxAttempts,
		&i.RetryBackoff,
		&i.ExecutionTimeout,
		&i.HeartbeatTimeout,
		&i.TimeoutAction,
		&i.SshCredentialID,
		&i.SsmProfileID,
		&i.K8sClusterID,
		&i.WorkerID,
		&i.WorkerLabels,
		&i.DependsOnProcessID,
		&i.DependencyType,
		&i.Environment,
		&i.Tags,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProcess = `-- name: DeleteProcess :execrows
DELETE FROM processes WHERE id = $1 AND workspace_id = $2
`

type DeleteProcessParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteProcess(ctx context.Context, arg DeleteProcessParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProcess, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDependentProcesses = `-- name: GetDependentProcesses :many
SELECT id, workspace_id, name, schedule_type, schedule, delay_duration, timezone, miss_policy, max_recovery_slots, allow_parallel, max_parallel, on_overlap, execution_method, runtime, method_config, max_attempts, retry_backoff, execution_timeout, heartbeat_timeout, timeout_action, ssh_credential_id, ssm_profile_id, k8s_cluster_id, worker_id, worker_labels, depends_on_process_id, dependency_type, environment, tags, enabled, created_at, updated_at FROM processes
WHERE depends_on_process_id = $1 AND enabled = true
`

func (q *Queries) GetDependentProcesses(ctx context.Context, dependsOnProcessID *string) ([]Process, error) {
	rows, err := q.db.Query(ctx, getDependentProcesses, dependsOnProcessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ScheduleType,
			&i.Schedule,
			&i.DelayDuration,
			&i.Timezone,
			&i.MissPolicy,
			&i.MaxRecoverySlots,
			&i.AllowParallel,
			&i.MaxParallel,
			&i.OnOverlap,
			&i.ExecutionMethod,
			&i.Runtime,
			&i.MethodConfig,
			&i.MaxAttempts,
			&i.RetryBackoff,
			&i.ExecutionTimeout,
			&i.HeartbeatTimeout,
			&i.TimeoutAction,
			&i.SshCredentialID,
			&i.SsmProfileID,
			&i.K8sClusterID,
			&i.WorkerID,
			&i.WorkerLabels,
			&i.DependsOnProcessID,
			&i.DependencyType,
			&i.Environment,
			&i.Tags,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcess = `-- name: GetProcess :one
SELECT id, workspace_id, name, schedule_type, schedule, delay_duration, timezone, miss_policy, max_recovery_slots, allow_parallel, max_parallel, on_overlap, execution_method, runtime, method_config, max_attempts, retry_backoff, execution_timeout, heartbeat_timeout, timeout_action, ssh_credential_id, ssm_profile_id, k8s_cluster_id, worker_id, worker_labels, depends_on_process_id, dependency_type, environment, tags, enabled, created_at, updated_at FROM processes WHERE id = $1 AND workspace_id = $2
`

type GetProcessParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetProcess(ctx context.Context, arg GetProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, getProcess, arg.ID, arg.WorkspaceID)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ScheduleType,
		&i.Schedule,
		&i.DelayDuration,
		&i.Timezone,
		&i.MissPolicy,
		&i.MaxRecoverySlots,
		&i.AllowParallel,
		&i.MaxParallel,
		&i.OnOverlap,
		&i.ExecutionMethod,
		&i.Runtime,
		&i.MethodConfig,
		&i.MaxAttempts,
		&i.RetryBackoff,
		&i.ExecutionTimeout,
		&i.HeartbeatTimeout,
		&i.TimeoutAction,
		&i.SshCredentialID,
		&i.SsmProfileID,
		&i.K8sClusterID,
		&i.WorkerID,
		&i.WorkerLabels,
		&i.DependsOnProcessID,
		&i.DependencyType,
		&i.Environment,
		&i.Tags,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProcessByName = `-- name: GetProcessByName :one
SELECT id, workspace_id, name, schedule_type, schedule, delay_duration, timezone, miss_policy, max_recovery_slots, allow_parallel, max_parallel, on_overlap, execution_method, runtime, method_config, max_attempts, retry_backoff, execution_timeout, heartbeat_timeout, timeout_action, ssh_credential_id, ssm_profile_id, k8s_cluster_id, worker_id, worker_labels, depends_on_process_id, dependency_type, environment, tags, enabled, created_at, updated_at FROM processes WHERE name = $1 AND workspace_id = $2
`

type GetProcessByNameParams struct {
	Name        string `json:"name"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetProcessByName(ctx context.Context, arg GetProcessByNameParams) (Process, error) {
	row := q.db.QueryRow(ctx, getProcessByName, arg.Name, arg.WorkspaceID)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ScheduleType,
		&i.Schedule,
		&i.DelayDuration,
		&i.Timezone,
		&i.MissPolicy,
		&i.MaxRecoverySlots,
		&i.AllowParallel,
		&i.MaxParallel,
		&i.OnOverlap,
		&i.ExecutionMethod,
		&i.Runtime,
		&i.MethodConfig,
		&i.MaxAttempts,
		&i.RetryBackoff,
		&i.ExecutionTimeout,
		&i.HeartbeatTimeout,
		&i.TimeoutAction,
		&i.SshCredentialID,
		&i.SsmProfileID,
		&i.K8sClusterID,
		&i.WorkerID,
		&i.WorkerLabels,
		&i.DependsOnProcessID,
		&i.DependencyType,
		&i.Environment,
		&i.Tags,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledCronProcesses = `-- name: ListEnabledCronProcesses :many
SELECT p.id, p.workspace_id, p.name, p.schedule_type, p.schedule, p.delay_duration, p.timezone, p.miss_policy, p.max_recovery_slots, p.allow_parallel, p.max_parallel, p.on_overlap, p.execution_method, p.runtime, p.method_config, p.max_attempts, p.retry_backoff, p.execution_timeout, p.heartbeat_timeout, p.timeout_action, p.ssh_credential_id, p.ssm_profile_id, p.k8s_cluster_id, p.worker_id, p.worker_labels, p.depends_on_process_id, p.dependency_type, p.environment, p.tags, p.enabled, p.created_at, p.updated_at, w.state AS workspace_state
FROM processes p
JOIN workspaces w ON w.id = p.workspace_id
WHERE p.enabled = true AND p.schedule_type = 'cron'
  AND w.state = 'active'
`

type ListEnabledCronProcessesRow struct {
	ID                 string             `json:"id"`
	WorkspaceID        string             `json:"workspace_id"`
	Name               string             `json:"name"`
	ScheduleType       string             `json:"schedule_type"`
	Schedule           *string            `json:"schedule"`
	DelayDuration      *string            `json:"delay_duration"`
	Timezone           *string            `json:"timezone"`
	MissPolicy         *string            `json:"miss_policy"`
	MaxRecoverySlots   int32              `json:"max_recovery_slots"`
	AllowParallel      bool               `json:"allow_parallel"`
	MaxParallel        int32              `json:"max_parallel"`
	OnOverlap          string             `json:"on_overlap"`
	ExecutionMethod    string             `json:"execution_method"`
	Runtime            string             `json:"runtime"`
	MethodConfig       []byte             `json:"method_config"`
	MaxAttempts        int32              `json:"max_attempts"`
	RetryBackoff       *string            `json:"retry_backoff"`
	ExecutionTimeout   pgtype.Interval    `json:"execution_timeout"`
	HeartbeatTimeout   pgtype.Interval    `json:"heartbeat_timeout"`
	TimeoutAction      string             `json:"timeout_action"`
	SshCredentialID    *string            `json:"ssh_credential_id"`
	SsmProfileID       *string            `json:"ssm_profile_id"`
	K8sClusterID       *string            `json:"k8s_cluster_id"`
	WorkerID           *string            `json:"worker_id"`
	WorkerLabels       []byte             `json:"worker_labels"`
	DependsOnProcessID *string            `json:"depends_on_process_id"`
	DependencyType     *string            `json:"dependency_type"`
	Environment        []byte             `json:"environment"`
	Tags               []string           `json:"tags"`
	Enabled            bool               `json:"enabled"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	WorkspaceState     string             `json:"workspace_state"`
}

func (q *Queries) ListEnabledCronProcesses(ctx context.Context) ([]ListEnabledCronProcessesRow, error) {
	rows, err := q.db.Query(ctx, listEnabledCronProcesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledCronProcessesRow{}
	for rows.Next() {
		var i ListEnabledCronProcessesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ScheduleType,
			&i.Schedule,
			&i.DelayDuration,
			&i.Timezone,
			&i.MissPolicy,
			&i.MaxRecoverySlots,
			&i.AllowParallel,
			&i.MaxParallel,
			&i.OnOverlap,
			&i.ExecutionMethod,
			&i.Runtime,
			&i.MethodConfig,
			&i.MaxAttempts,
			&i.RetryBackoff,
			&i.ExecutionTimeout,
			&i.HeartbeatTimeout,
			&i.TimeoutAction,
			&i.SshCredentialID,
			&i.SsmProfileID,
			&i.K8sClusterID,
			&i.WorkerID,
			&i.WorkerLabels,
			&i.DependsOnProcessID,
			&i.DependencyType,
			&i.Environment,
			&i.Tags,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledFixedDelayProcesses = `-- name: ListEnabledFixedDelayProcesses :many
SELECT p.id, p.workspace_id, p.name, p.schedule_type, p.schedule, p.delay_duration, p.timezone, p.miss_policy, p.max_recovery_slots, p.allow_parallel, p.max_parallel, p.on_overlap, p.execution_method, p.runtime, p.method_config, p.max_attempts, p.retry_backoff, p.execution_timeout, p.heartbeat_timeout, p.timeout_action, p.ssh_credential_id, p.ssm_profile_id, p.k8s_cluster_id, p.worker_id, p.worker_labels, p.depends_on_process_id, p.dependency_type, p.environment, p.tags, p.enabled, p.created_at, p.updated_at, w.state AS workspace_state
FROM processes p
JOIN workspaces w ON w.id = p.workspace_id
WHERE p.enabled = true AND p.schedule_type = 'fixed_delay'
  AND w.state = 'active'
`

type ListEnabledFixedDelayProcessesRow struct {
	ID                 string             `json:"id"`
	WorkspaceID        string             `json:"workspace_id"`
	Name               string             `json:"name"`
	ScheduleType       string             `json:"schedule_type"`
	Schedule           *string            `json:"schedule"`
	DelayDuration      *string            `json:"delay_duration"`
	Timezone           *string            `json:"timezone"`
	MissPolicy         *string            `json:"miss_policy"`
	MaxRecoverySlots   int32              `json:"max_recovery_slots"`
	AllowParallel      bool               `json:"allow_parallel"`
	MaxParallel        int32              `json:"max_parallel"`
	OnOverlap          string             `json:"on_overlap"`
	ExecutionMethod    string             `json:"execution_method"`
	Runtime            string             `json:"runtime"`
	MethodConfig       []byte             `json:"method_config"`
	MaxAttempts        int32              `json:"max_attempts"`
	RetryBackoff       *string            `json:"retry_backoff"`
	ExecutionTimeout   pgtype.Interval    `json:"execution_timeout"`
	HeartbeatTimeout   pgtype.Interval    `json:"heartbeat_timeout"`
	TimeoutAction      string             `json:"timeout_action"`
	SshCredentialID    *string            `json:"ssh_credential_id"`
	SsmProfileID       *string            `json:"ssm_profile_id"`
	K8sClusterID       *string            `json:"k8s_cluster_id"`
	WorkerID           *string            `json:"worker_id"`
	WorkerLabels       []byte             `json:"worker_labels"`
	DependsOnProcessID *string            `json:"depends_on_process_id"`
	DependencyType     *string            `json:"dependency_type"`
	Environment        []byte             `json:"environment"`
	Tags               []string           `json:"tags"`
	Enabled            bool               `json:"enabled"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	WorkspaceState     string             `json:"workspace_state"`
}

func (q *Queries) ListEnabledFixedDelayProcesses(ctx context.Context) ([]ListEnabledFixedDelayProcessesRow, error) {
	rows, err := q.db.Query(ctx, listEnabledFixedDelayProcesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledFixedDelayProcessesRow{}
	for rows.Next() {
		var i ListEnabledFixedDelayProcessesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ScheduleType,
			&i.Schedule,
			&i.DelayDuration,
			&i.Timezone,
			&i.MissPolicy,
			&i.MaxRecoverySlots,
			&i.AllowParallel,
			&i.MaxParallel,
			&i.OnOverlap,
			&i.ExecutionMethod,
			&i.Runtime,
			&i.MethodConfig,
			&i.MaxAttempts,
			&i.RetryBackoff,
			&i.ExecutionTimeout,
			&i.HeartbeatTimeout,
			&i.TimeoutAction,
			&i.SshCredentialID,
			&i.SsmProfileID,
			&i.K8sClusterID,
			&i.WorkerID,
			&i.WorkerLabels,
			&i.DependsOnProcessID,
			&i.DependencyType,
			&i.Environment,
			&i.Tags,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcesses = `-- name: ListProcesses :many
SELECT id, workspace_id, name, schedule_type, schedule, delay_duration, timezone, miss_policy, max_recovery_slots, allow_parallel, max_parallel, on_overlap, execution_method, runtime, method_config, max_attempts, retry_backoff, execution_timeout, heartbeat_timeout, timeout_action, ssh_credential_id, ssm_profile_id, k8s_cluster_id, worker_id, worker_labels, depends_on_process_id, dependency_type, environment, tags, enabled, created_at, updated_at FROM processes
WHERE workspace_id = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListProcessesParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListProcesses(ctx context.Context, arg ListProcessesParams) ([]Process, error) {
	rows, err := q.db.Query(ctx, listProcesses, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ScheduleType,
			&i.Schedule,
			&i.DelayDuration,
			&i.Timezone,
			&i.MissPolicy,
			&i.MaxRecoverySlots,
			&i.AllowParallel,
			&i.MaxParallel,
			&i.OnOverlap,
			&i.ExecutionMethod,
			&i.Runtime,
			&i.MethodConfig,
			&i.MaxAttempts,
			&i.RetryBackoff,
			&i.ExecutionTimeout,
			&i.HeartbeatTimeout,
			&i.TimeoutAction,
			&i.SshCredentialID,
			&i.SsmProfileID,
			&i.K8sClusterID,
			&i.WorkerID,
			&i.WorkerLabels,
			&i.DependsOnProcessID,
			&i.DependencyType,
			&i.Environment,
			&i.Tags,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProcessEnabled = `-- name: SetProcessEnabled :exec
UPDATE processes SET enabled = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2
`

type SetProcessEnabledParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) SetProcessEnabled(ctx context.Context, arg SetProcessEnabledParams) error {
	_, err := q.db.Exec(ctx, setProcessEnabled, arg.ID, arg.WorkspaceID, arg.Enabled)
	return err
}

const updateProcess = `-- name: UpdateProcess :one
UPDATE processes SET
    name = $3, schedule_type = $4, schedule = $5, delay_duration = $6, timezone = $7,
    miss_policy = $8, max_recovery_slots = $9, allow_parallel = $10, max_parallel = $11, on_overlap = $12,
    execution_method = $13, runtime = $14, method_config = $15,
    max_attempts = $16, retry_backoff = $17, execution_timeout = $18, heartbeat_timeout = $19, timeout_action = $20,
    ssh_credential_id = $21, ssm_profile_id = $22, k8s_cluster_id = $23,
    worker_id = $24, worker_labels = $25,
    depends_on_process_id = $26, dependency_type = $27,
    environment = $28, tags = $29, enabled = $30,
    updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, schedule_type, schedule, delay_duration, timezone, miss_policy, max_recovery_slots, allow_parallel, max_parallel, on_overlap, execution_method, runtime, method_config, max_attempts, retry_backoff, execution_timeout, heartbeat_timeout, timeout_action, ssh_credential_id, ssm_profile_id, k8s_cluster_id, worker_id, worker_labels, depends_on_process_id, dependency_type, environment, tags, enabled, created_at, updated_at
`

type UpdateProcessParams struct {
	ID                 string          `json:"id"`
	WorkspaceID        string          `json:"workspace_id"`
	Name               string          `json:"name"`
	ScheduleType       string          `json:"schedule_type"`
	Schedule           *string         `json:"schedule"`
	DelayDuration      *string         `json:"delay_duration"`
	Timezone           *string         `json:"timezone"`
	MissPolicy         *string         `json:"miss_policy"`
	MaxRecoverySlots   int32           `json:"max_recovery_slots"`
	AllowParallel      bool            `json:"allow_parallel"`
	MaxParallel        int32           `json:"max_parallel"`
	OnOverlap          string          `json:"on_overlap"`
	ExecutionMethod    string          `json:"execution_method"`
	Runtime            string          `json:"runtime"`
	MethodConfig       []byte          `json:"method_config"`
	MaxAttempts        int32           `json:"max_attempts"`
	RetryBackoff       *string         `json:"retry_backoff"`
	ExecutionTimeout   pgtype.Interval `json:"execution_timeout"`
	HeartbeatTimeout   pgtype.Interval `json:"heartbeat_timeout"`
	TimeoutAction      string          `json:"timeout_action"`
	SshCredentialID    *string         `json:"ssh_credential_id"`
	SsmProfileID       *string         `json:"ssm_profile_id"`
	K8sClusterID       *string         `json:"k8s_cluster_id"`
	WorkerID           *string         `json:"worker_id"`
	WorkerLabels       []byte          `json:"worker_labels"`
	DependsOnProcessID *string         `json:"depends_on_process_id"`
	DependencyType     *string         `json:"dependency_type"`
	Environment        []byte          `json:"environment"`
	Tags               []string        `json:"tags"`
	Enabled            bool            `json:"enabled"`
}

func (q *Queries) UpdateProcess(ctx context.Context, arg UpdateProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, updateProcess,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ScheduleType,
		arg.Schedule,
		arg.DelayDuration,
		arg.Timezone,
		arg.MissPolicy,
		arg.MaxRecoverySlots,
		arg.AllowParallel,
		arg.MaxParallel,
		arg.OnOverlap,
		arg.ExecutionMethod,
		arg.Runtime,
		arg.MethodConfig,
		arg.MaxAttempts,
		arg.RetryBackoff,
		arg.ExecutionTimeout,
		arg.HeartbeatTimeout,
		arg.TimeoutAction,
		arg.SshCredentialID,
		arg.SsmProfileID,
		arg.K8sClusterID,
		arg.WorkerID,
		arg.WorkerLabels,
		arg.DependsOnProcessID,
		arg.DependencyType,
		arg.Environment,
		arg.Tags,
		arg.Enabled,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ScheduleType,
		&i.Schedule,
		&i.DelayDuration,
		&i.Timezone,
		&i.MissPolicy,
		&i.MaxRecoverySlots,
		&i.AllowParallel,
		&i.MaxParallel,
		&i.OnOverlap,
		&i.ExecutionMethod,
		&i.Runtime,
		&i.MethodConfig,
		&i.MaxAttempts,
		&i.RetryBackoff,
		&i.ExecutionTimeout,
		&i.HeartbeatTimeout,
		&i.TimeoutAction,
		&i.SshCredentialID,
		&i.SsmProfileID,
		&i.K8sClusterID,
		&i.WorkerID,
		&i.WorkerLabels,
		&i.DependsOnProcessID,
		&i.DependencyType,
		&i.Environment,
		&i.Tags,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
