// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countQueues = `-- name: CountQueues :one
SELECT count(*) FROM queues WHERE workspace_id = $1
`

func (q *Queries) CountQueues(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countQueues, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQueue = `-- name: CreateQueue :one
INSERT INTO queues (
    id, workspace_id, name, execution_method, runtime, method_config,
    concurrency, max_attempts, retry_backoff, job_timeout, max_response_size,
    ssh_credential_id, ssm_profile_id, k8s_cluster_id,
    worker_id, worker_labels, tags, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17, $18
)
RETURNING id, workspace_id, name, execution_method, runtime, method_config, concurrency, max_attempts, retry_backoff, job_timeout, max_response_size, ssh_credential_id, ssm_profile_id, k8s_cluster_id, worker_id, worker_labels, tags, enabled, created_at, updated_at
`

type CreateQueueParams struct {
	ID              string          `json:"id"`
	WorkspaceID     string          `json:"workspace_id"`
	Name            string          `json:"name"`
	ExecutionMethod string          `json:"execution_method"`
	Runtime         string          `json:"runtime"`
	MethodConfig    []byte          `json:"method_config"`
	Concurrency     int32           `json:"concurrency"`
	MaxAttempts     int32           `json:"max_attempts"`
	RetryBackoff    string          `json:"retry_backoff"`
	JobTimeout      pgtype.Interval `json:"job_timeout"`
	MaxResponseSize int32           `json:"max_response_size"`
	SshCredentialID *string         `json:"ssh_credential_id"`
	SsmProfileID    *string         `json:"ssm_profile_id"`
	K8sClusterID    *string         `json:"k8s_cluster_id"`
	WorkerID        *string         `json:"worker_id"`
	WorkerLabels    []byte          `json:"worker_labels"`
	Tags            []string        `json:"tags"`
	Enabled         bool            `json:"enabled"`
}

func (q *Queries) CreateQueue(ctx context.Context, arg CreateQueueParams) (Queue, error) {
	row := q.db.QueryRow(ctx, createQueue,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ExecutionMethod,
		arg.Runtime,
		arg.MethodConfig,
		arg.Concurrency,
		arg.MaxAttempts,
		arg.RetryBackoff,
		arg.JobTimeout,
		arg.MaxResponseSize,
		arg.SshCredentialID,
		arg.SsmProfileID,
		arg.K8sClusterID,
		arg.WorkerID,
		arg.WorkerLabels,
		arg.Tags,
		arg.Enabled,
	)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ExecutionMethod,
		&i.Runtime,
		&i.MethodConfig,
		&i.Concurrency,
		&i.MaxAttempts,
		&i.RetryBackoff,
		&i.JobTimeout,
		&i.MaxResponseSize,
		&i.SshCredentialID,
		&i.SsmProfileID,
		&i.K8sClusterID,
		&i.WorkerID,
		&i.WorkerLabels,
		&i.Tags,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQueue = `-- name: DeleteQueue :execrows
DELETE FROM queues WHERE id = $1 AND workspace_id = $2
`

type DeleteQueueParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteQueue(ctx context.Context, arg DeleteQueueParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQueue, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQueue = `-- name: GetQueue :one
SELECT id, workspace_id, name, execution_method, runtime, method_config, concurrency, max_attempts, retry_backoff, job_timeout, max_response_size, ssh_credential_id, ssm_profile_id, k8s_cluster_id, worker_id, worker_labels, tags, enabled, created_at, updated_at FROM queues WHERE id = $1 AND workspace_id = $2
`

type GetQueueParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetQueue(ctx context.Context, arg GetQueueParams) (Queue, error) {
	row := q.db.QueryRow(ctx, getQueue, arg.ID, arg.WorkspaceID)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ExecutionMethod,
		&i.Runtime,
		&i.MethodConfig,
		&i.Concurrency,
		&i.MaxAttempts,
		&i.RetryBackoff,
		&i.JobTimeout,
		&i.MaxResponseSize,
		&i.SshCredentialID,
		&i.SsmProfileID,
		&i.K8sClusterID,
		&i.WorkerID,
		&i.WorkerLabels,
		&i.Tags,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueueStats = `-- name: GetQueueStats :one
SELECT
    q.id,
    q.name,
    (SELECT count(*) FROM jobs j WHERE j.queue_id = q.id AND j.state = 'pending') AS pending_count,
    (SELECT count(*) FROM jobs j WHERE j.queue_id = q.id AND j.state = 'running') AS running_count,
    (SELECT count(*) FROM jobs j WHERE j.queue_id = q.id AND j.state = 'retrying') AS retrying_count,
    (SELECT count(*) FROM jobs j WHERE j.queue_id = q.id AND j.state = 'failed'
        AND j.updated_at >= now() - interval '24 hours') AS failed_24h,
    (SELECT count(*) FROM jobs j WHERE j.queue_id = q.id AND j.state = 'completed'
        AND j.updated_at >= now() - interval '24 hours') AS completed_24h
FROM queues q
WHERE q.id = $1 AND q.workspace_id = $2
`

type GetQueueStatsParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

type GetQueueStatsRow struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	PendingCount  int64  `json:"pending_count"`
	RunningCount  int64  `json:"running_count"`
	RetryingCount int64  `json:"retrying_count"`
	Failed24h     int64  `json:"failed_24h"`
	Completed24h  int64  `json:"completed_24h"`
}

func (q *Queries) GetQueueStats(ctx context.Context, arg GetQueueStatsParams) (GetQueueStatsRow, error) {
	row := q.db.QueryRow(ctx, getQueueStats, arg.ID, arg.WorkspaceID)
	var i GetQueueStatsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PendingCount,
		&i.RunningCount,
		&i.RetryingCount,
		&i.Failed24h,
		&i.Completed24h,
	)
	return i, err
}

const listQueues = `-- name: ListQueues :many
SELECT id, workspace_id, name, execution_method, runtime, method_config, concurrency, max_attempts, retry_backoff, job_timeout, max_response_size, ssh_credential_id, ssm_profile_id, k8s_cluster_id, worker_id, worker_labels, tags, enabled, created_at, updated_at FROM queues WHERE workspace_id = $1 ORDER BY name
`

func (q *Queries) ListQueues(ctx context.Context, workspaceID string) ([]Queue, error) {
	rows, err := q.db.Query(ctx, listQueues, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Queue{}
	for rows.Next() {
		var i Queue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ExecutionMethod,
			&i.Runtime,
			&i.MethodConfig,
			&i.Concurrency,
			&i.MaxAttempts,
			&i.RetryBackoff,
			&i.JobTimeout,
			&i.MaxResponseSize,
			&i.SshCredentialID,
			&i.SsmProfileID,
			&i.K8sClusterID,
			&i.WorkerID,
			&i.WorkerLabels,
			&i.Tags,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setQueueEnabled = `-- name: SetQueueEnabled :exec
UPDATE queues SET enabled = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2
`

type SetQueueEnabledParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) SetQueueEnabled(ctx context.Context, arg SetQueueEnabledParams) error {
	_, err := q.db.Exec(ctx, setQueueEnabled, arg.ID, arg.WorkspaceID, arg.Enabled)
	return err
}

const updateQueue = `-- name: UpdateQueue :one
UPDATE queues SET
    name = $3, execution_method = $4, runtime = $5, method_config = $6,
    concurrency = $7, max_attempts = $8, retry_backoff = $9, job_timeout = $10, max_response_size = $11,
    ssh_credential_id = $12, ssm_profile_id = $13, k8s_cluster_id = $14,
    worker_id = $15, worker_labels = $16, tags = $17, enabled = $18,
    updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, execution_method, runtime, method_config, concurrency, max_attempts, retry_backoff, job_timeout, max_response_size, ssh_credential_id, ssm_profile_id, k8s_cluster_id, worker_id, worker_labels, tags, enabled, created_at, updated_at
`

type UpdateQueueParams struct {
	ID              string          `json:"id"`
	WorkspaceID     string          `json:"workspace_id"`
	Name            string          `json:"name"`
	ExecutionMethod string          `json:"execution_method"`
	Runtime         string          `json:"runtime"`
	MethodConfig    []byte          `json:"method_config"`
	Concurrency     int32           `json:"concurrency"`
	MaxAttempts     int32           `json:"max_attempts"`
	RetryBackoff    string          `json:"retry_backoff"`
	JobTimeout      pgtype.Interval `json:"job_timeout"`
	MaxResponseSize int32           `json:"max_response_size"`
	SshCredentialID *string         `json:"ssh_credential_id"`
	SsmProfileID    *string         `json:"ssm_profile_id"`
	K8sClusterID    *string         `json:"k8s_cluster_id"`
	WorkerID        *string         `json:"worker_id"`
	WorkerLabels    []byte          `json:"worker_labels"`
	Tags            []string        `json:"tags"`
	Enabled         bool            `json:"enabled"`
}

func (q *Queries) UpdateQueue(ctx context.Context, arg UpdateQueueParams) (Queue, error) {
	row := q.db.QueryRow(ctx, updateQueue,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ExecutionMethod,
		arg.Runtime,
		arg.MethodConfig,
		arg.Concurrency,
		arg.MaxAttempts,
		arg.RetryBackoff,
		arg.JobTimeout,
		arg.MaxResponseSize,
		arg.SshCredentialID,
		arg.SsmProfileID,
		arg.K8sClusterID,
		arg.WorkerID,
		arg.WorkerLabels,
		arg.Tags,
		arg.Enabled,
	)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ExecutionMethod,
		&i.Runtime,
		&i.MethodConfig,
		&i.Concurrency,
		&i.MaxAttempts,
		&i.RetryBackoff,
		&i.JobTimeout,
		&i.MaxResponseSize,
		&i.SshCredentialID,
		&i.SsmProfileID,
		&i.K8sClusterID,
		&i.WorkerID,
		&i.WorkerLabels,
		&i.Tags,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
