// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRunAttempt = `-- name: CreateRunAttempt :one
INSERT INTO run_attempts (id, run_id, attempt_number, started_at, worker_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, attempt_number, started_at, finished_at, duration_ms, exit_code, worker_id, error_message, created_at
`

type CreateRunAttemptParams struct {
	ID            string             `json:"id"`
	RunID         string             `json:"run_id"`
	AttemptNumber int32              `json:"attempt_number"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	WorkerID      *string            `json:"worker_id"`
}

func (q *Queries) CreateRunAttempt(ctx context.Context, arg CreateRunAttemptParams) (RunAttempt, error) {
	row := q.db.QueryRow(ctx, createRunAttempt,
		arg.ID,
		arg.RunID,
		arg.AttemptNumber,
		arg.StartedAt,
		arg.WorkerID,
	)
	var i RunAttempt
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AttemptNumber,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ExitCode,
		&i.WorkerID,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const finishRunAttempt = `-- name: FinishRunAttempt :exec
UPDATE run_attempts SET
    finished_at = $2,
    duration_ms = $3,
    exit_code = $4,
    error_message = $5
WHERE id = $1
`

type FinishRunAttemptParams struct {
	ID           string             `json:"id"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	DurationMs   *int64             `json:"duration_ms"`
	ExitCode     *int32             `json:"exit_code"`
	ErrorMessage *string            `json:"error_message"`
}

func (q *Queries) FinishRunAttempt(ctx context.Context, arg FinishRunAttemptParams) error {
	_, err := q.db.Exec(ctx, finishRunAttempt,
		arg.ID,
		arg.FinishedAt,
		arg.DurationMs,
		arg.ExitCode,
		arg.ErrorMessage,
	)
	return err
}

const listRunAttemptsByRun = `-- name: ListRunAttemptsByRun :many
SELECT id, run_id, attempt_number, started_at, finished_at, duration_ms, exit_code, worker_id, error_message, created_at FROM run_attempts WHERE run_id = $1 ORDER BY attempt_number
`

func (q *Queries) ListRunAttemptsByRun(ctx context.Context, runID string) ([]RunAttempt, error) {
	rows, err := q.db.Query(ctx, listRunAttemptsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunAttempt{}
	for rows.Next() {
		var i RunAttempt
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AttemptNumber,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ExitCode,
			&i.WorkerID,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
