// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_output.sql

package db

import (
	"context"
)

const appendRunOutput = `-- name: AppendRunOutput :one
INSERT INTO run_output (id, run_id, stream, content, truncated)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, stream, content, truncated, created_at
`

type AppendRunOutputParams struct {
	ID        string `json:"id"`
	RunID     string `json:"run_id"`
	Stream    string `json:"stream"`
	Content   string `json:"content"`
	Truncated bool   `json:"truncated"`
}

func (q *Queries) AppendRunOutput(ctx context.Context, arg AppendRunOutputParams) (RunOutput, error) {
	row := q.db.QueryRow(ctx, appendRunOutput,
		arg.ID,
		arg.RunID,
		arg.Stream,
		arg.Content,
		arg.Truncated,
	)
	var i RunOutput
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Stream,
		&i.Content,
		&i.Truncated,
		&i.CreatedAt,
	)
	return i, err
}

const getRunOutput = `-- name: GetRunOutput :many
SELECT id, run_id, stream, content, truncated, created_at FROM run_output
WHERE run_id = $1
  AND ($2::text IS NULL OR stream = $2)
ORDER BY created_at
`

type GetRunOutputParams struct {
	RunID   string `json:"run_id"`
	Column2 string `json:"column_2"`
}

func (q *Queries) GetRunOutput(ctx context.Context, arg GetRunOutputParams) ([]RunOutput, error) {
	rows, err := q.db.Query(ctx, getRunOutput, arg.RunID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunOutput{}
	for rows.Next() {
		var i RunOutput
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Stream,
			&i.Content,
			&i.Truncated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
