// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkCancelRuns = `-- name: BulkCancelRuns :execrows
UPDATE runs SET state = 'cancelled', updated_at = now()
WHERE process_id = $1 AND workspace_id = $2 AND state = 'pending'
`

type BulkCancelRunsParams struct {
	ProcessID   string `json:"process_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) BulkCancelRuns(ctx context.Context, arg BulkCancelRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkCancelRuns, arg.ProcessID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkPauseRuns = `-- name: BulkPauseRuns :execrows
UPDATE runs SET state = 'paused', updated_at = now()
WHERE process_id = $1 AND workspace_id = $2 AND state = 'pending'
`

type BulkPauseRunsParams struct {
	ProcessID   string `json:"process_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) BulkPauseRuns(ctx context.Context, arg BulkPauseRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkPauseRuns, arg.ProcessID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkResumeRuns = `-- name: BulkResumeRuns :execrows
UPDATE runs SET state = 'pending', updated_at = now()
WHERE process_id = $1 AND workspace_id = $2 AND state = 'paused'
`

type BulkResumeRunsParams struct {
	ProcessID   string `json:"process_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) BulkResumeRuns(ctx context.Context, arg BulkResumeRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkResumeRuns, arg.ProcessID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimPendingRuns = `-- name: ClaimPendingRuns :many
SELECT r.id, r.workspace_id, r.process_id, r.scheduled_at, r.state, r.origin, r.attempt, r.max_attempts, r.next_attempt_at, r.started_at, r.finished_at, r.duration_ms, r.exit_code, r.progress_total, r.progress_current, r.progress, r.progress_message, r.last_heartbeat_at, r.queue_reason, r.waiting_reason, r.actor_type, r.actor_id, r.killed_by_actor_type, r.killed_by_actor_id, r.triggered_by_run_id, r.replayed_from_run_id, r.effective_config, r.runtime, r.worker_id, r.tags, r.created_at, r.updated_at
FROM runs r
JOIN workspaces w ON w.id = r.workspace_id
WHERE r.state IN ('pending', 'queued')
  AND r.scheduled_at <= now()
  AND w.state = 'active'
ORDER BY r.scheduled_at
LIMIT $1
FOR UPDATE OF r SKIP LOCKED
`

func (q *Queries) ClaimPendingRuns(ctx context.Context, limit int32) ([]Run, error) {
	rows, err := q.db.Query(ctx, claimPendingRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProcessID,
			&i.ScheduledAt,
			&i.State,
			&i.Origin,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ExitCode,
			&i.ProgressTotal,
			&i.ProgressCurrent,
			&i.Progress,
			&i.ProgressMessage,
			&i.LastHeartbeatAt,
			&i.QueueReason,
			&i.WaitingReason,
			&i.ActorType,
			&i.ActorID,
			&i.KilledByActorType,
			&i.KilledByActorID,
			&i.TriggeredByRunID,
			&i.ReplayedFromRunID,
			&i.EffectiveConfig,
			&i.Runtime,
			&i.WorkerID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimRetryingRuns = `-- name: ClaimRetryingRuns :many
SELECT r.id, r.workspace_id, r.process_id, r.scheduled_at, r.state, r.origin, r.attempt, r.max_attempts, r.next_attempt_at, r.started_at, r.finished_at, r.duration_ms, r.exit_code, r.progress_total, r.progress_current, r.progress, r.progress_message, r.last_heartbeat_at, r.queue_reason, r.waiting_reason, r.actor_type, r.actor_id, r.killed_by_actor_type, r.killed_by_actor_id, r.triggered_by_run_id, r.replayed_from_run_id, r.effective_config, r.runtime, r.worker_id, r.tags, r.created_at, r.updated_at
FROM runs r
JOIN workspaces w ON w.id = r.workspace_id
WHERE r.state = 'retrying'
  AND r.next_attempt_at <= now()
  AND w.state = 'active'
ORDER BY r.next_attempt_at
LIMIT $1
FOR UPDATE OF r SKIP LOCKED
`

func (q *Queries) ClaimRetryingRuns(ctx context.Context, limit int32) ([]Run, error) {
	rows, err := q.db.Query(ctx, claimRetryingRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProcessID,
			&i.ScheduledAt,
			&i.State,
			&i.Origin,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ExitCode,
			&i.ProgressTotal,
			&i.ProgressCurrent,
			&i.Progress,
			&i.ProgressMessage,
			&i.LastHeartbeatAt,
			&i.QueueReason,
			&i.WaitingReason,
			&i.ActorType,
			&i.ActorID,
			&i.KilledByActorType,
			&i.KilledByActorID,
			&i.TriggeredByRunID,
			&i.ReplayedFromRunID,
			&i.EffectiveConfig,
			&i.Runtime,
			&i.WorkerID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveByProcess = `-- name: CountActiveByProcess :one
SELECT count(*) FROM runs
WHERE process_id = $1 AND state IN ('running', 'retrying', 'waiting_for_worker')
`

func (q *Queries) CountActiveByProcess(ctx context.Context, processID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveByProcess, processID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunningByWorkspace = `-- name: CountRunningByWorkspace :one
SELECT count(*) FROM runs WHERE workspace_id = $1 AND state = 'running'
`

func (q *Queries) CountRunningByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRuns = `-- name: CountRuns :one
SELECT count(*) FROM runs
WHERE workspace_id = $1
  AND ($2 = '' OR process_id = $2)
  AND ($3 = '' OR state = $3)
  AND ($4 = '' OR origin = $4)
`

type CountRunsParams struct {
	WorkspaceID string      `json:"workspace_id"`
	Column2     interface{} `json:"column_2"`
	Column3     interface{} `json:"column_3"`
	Column4     interface{} `json:"column_4"`
}

func (q *Queries) CountRuns(ctx context.Context, arg CountRunsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRuns,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (
    id, workspace_id, process_id, scheduled_at, state, origin,
    max_attempts, actor_type, actor_id,
    triggered_by_run_id, replayed_from_run_id,
    runtime, worker_id, tags
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11,
    $12, $13, $14
)
RETURNING id, workspace_id, process_id, scheduled_at, state, origin, attempt, max_attempts, next_attempt_at, started_at, finished_at, duration_ms, exit_code, progress_total, progress_current, progress, progress_message, last_heartbeat_at, queue_reason, waiting_reason, actor_type, actor_id, killed_by_actor_type, killed_by_actor_id, triggered_by_run_id, replayed_from_run_id, effective_config, runtime, worker_id, tags, created_at, updated_at
`

type CreateRunParams struct {
	ID                string             `json:"id"`
	WorkspaceID       string             `json:"workspace_id"`
	ProcessID         string             `json:"process_id"`
	ScheduledAt       pgtype.Timestamptz `json:"scheduled_at"`
	State             string             `json:"state"`
	Origin            string             `json:"origin"`
	MaxAttempts       int32              `json:"max_attempts"`
	ActorType         *string            `json:"actor_type"`
	ActorID           *string            `json:"actor_id"`
	TriggeredByRunID  *string            `json:"triggered_by_run_id"`
	ReplayedFromRunID *string            `json:"replayed_from_run_id"`
	Runtime           *string            `json:"runtime"`
	WorkerID          *string            `json:"worker_id"`
	Tags              []string           `json:"tags"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.WorkspaceID,
		arg.ProcessID,
		arg.ScheduledAt,
		arg.State,
		arg.Origin,
		arg.MaxAttempts,
		arg.ActorType,
		arg.ActorID,
		arg.TriggeredByRunID,
		arg.ReplayedFromRunID,
		arg.Runtime,
		arg.WorkerID,
		arg.Tags,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProcessID,
		&i.ScheduledAt,
		&i.State,
		&i.Origin,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ExitCode,
		&i.ProgressTotal,
		&i.ProgressCurrent,
		&i.Progress,
		&i.ProgressMessage,
		&i.LastHeartbeatAt,
		&i.QueueReason,
		&i.WaitingReason,
		&i.ActorType,
		&i.ActorID,
		&i.KilledByActorType,
		&i.KilledByActorID,
		&i.TriggeredByRunID,
		&i.ReplayedFromRunID,
		&i.EffectiveConfig,
		&i.Runtime,
		&i.WorkerID,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastRunByProcess = `-- name: GetLastRunByProcess :one
SELECT id, workspace_id, process_id, scheduled_at, state, origin, attempt, max_attempts, next_attempt_at, started_at, finished_at, duration_ms, exit_code, progress_total, progress_current, progress, progress_message, last_heartbeat_at, queue_reason, waiting_reason, actor_type, actor_id, killed_by_actor_type, killed_by_actor_id, triggered_by_run_id, replayed_from_run_id, effective_config, runtime, worker_id, tags, created_at, updated_at FROM runs
WHERE process_id = $1
ORDER BY scheduled_at DESC
LIMIT 1
`

func (q *Queries) GetLastRunByProcess(ctx context.Context, processID string) (Run, error) {
	row := q.db.QueryRow(ctx, getLastRunByProcess, processID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProcessID,
		&i.ScheduledAt,
		&i.State,
		&i.Origin,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ExitCode,
		&i.ProgressTotal,
		&i.ProgressCurrent,
		&i.Progress,
		&i.ProgressMessage,
		&i.LastHeartbeatAt,
		&i.QueueReason,
		&i.WaitingReason,
		&i.ActorType,
		&i.ActorID,
		&i.KilledByActorType,
		&i.KilledByActorID,
		&i.TriggeredByRunID,
		&i.ReplayedFromRunID,
		&i.EffectiveConfig,
		&i.Runtime,
		&i.WorkerID,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, workspace_id, process_id, scheduled_at, state, origin, attempt, max_attempts, next_attempt_at, started_at, finished_at, duration_ms, exit_code, progress_total, progress_current, progress, progress_message, last_heartbeat_at, queue_reason, waiting_reason, actor_type, actor_id, killed_by_actor_type, killed_by_actor_id, triggered_by_run_id, replayed_from_run_id, effective_config, runtime, worker_id, tags, created_at, updated_at FROM runs WHERE id = $1 AND workspace_id = $2
`

type GetRunParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.WorkspaceID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProcessID,
		&i.ScheduledAt,
		&i.State,
		&i.Origin,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ExitCode,
		&i.ProgressTotal,
		&i.ProgressCurrent,
		&i.Progress,
		&i.ProgressMessage,
		&i.LastHeartbeatAt,
		&i.QueueReason,
		&i.WaitingReason,
		&i.ActorType,
		&i.ActorID,
		&i.KilledByActorType,
		&i.KilledByActorID,
		&i.TriggeredByRunID,
		&i.ReplayedFromRunID,
		&i.EffectiveConfig,
		&i.Runtime,
		&i.WorkerID,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunWithProcess = `-- name: GetRunWithProcess :one
SELECT r.id, r.workspace_id, r.process_id, r.scheduled_at, r.state, r.origin, r.attempt, r.max_attempts, r.next_attempt_at, r.started_at, r.finished_at, r.duration_ms, r.exit_code, r.progress_total, r.progress_current, r.progress, r.progress_message, r.last_heartbeat_at, r.queue_reason, r.waiting_reason, r.actor_type, r.actor_id, r.killed_by_actor_type, r.killed_by_actor_id, r.triggered_by_run_id, r.replayed_from_run_id, r.effective_config, r.runtime, r.worker_id, r.tags, r.created_at, r.updated_at, p.name AS process_name, p.execution_method, p.method_config,
       p.execution_timeout, p.heartbeat_timeout, p.timeout_action,
       p.max_attempts AS process_max_attempts, p.retry_backoff AS process_retry_backoff
FROM runs r
JOIN processes p ON p.id = r.process_id
WHERE r.id = $1 AND r.workspace_id = $2
`

type GetRunWithProcessParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

type GetRunWithProcessRow struct {
	ID                  string             `json:"id"`
	WorkspaceID         string             `json:"workspace_id"`
	ProcessID           string             `json:"process_id"`
	ScheduledAt         pgtype.Timestamptz `json:"scheduled_at"`
	State               string             `json:"state"`
	Origin              string             `json:"origin"`
	Attempt             int32              `json:"attempt"`
	MaxAttempts         int32              `json:"max_attempts"`
	NextAttemptAt       pgtype.Timestamptz `json:"next_attempt_at"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
	DurationMs          *int64             `json:"duration_ms"`
	ExitCode            *int32             `json:"exit_code"`
	ProgressTotal       *int32             `json:"progress_total"`
	ProgressCurrent     *int32             `json:"progress_current"`
	Progress            *int32             `json:"progress"`
	ProgressMessage     *string            `json:"progress_message"`
	LastHeartbeatAt     pgtype.Timestamptz `json:"last_heartbeat_at"`
	QueueReason         *string            `json:"queue_reason"`
	WaitingReason       *string            `json:"waiting_reason"`
	ActorType           *string            `json:"actor_type"`
	ActorID             *string            `json:"actor_id"`
	KilledByActorType   *string            `json:"killed_by_actor_type"`
	KilledByActorID     *string            `json:"killed_by_actor_id"`
	TriggeredByRunID    *string            `json:"triggered_by_run_id"`
	ReplayedFromRunID   *string            `json:"replayed_from_run_id"`
	EffectiveConfig     []byte             `json:"effective_config"`
	Runtime             *string            `json:"runtime"`
	WorkerID            *string            `json:"worker_id"`
	Tags                []string           `json:"tags"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ProcessName         string             `json:"process_name"`
	ExecutionMethod     string             `json:"execution_method"`
	MethodConfig        []byte             `json:"method_config"`
	ExecutionTimeout    pgtype.Interval    `json:"execution_timeout"`
	HeartbeatTimeout    pgtype.Interval    `json:"heartbeat_timeout"`
	TimeoutAction       string             `json:"timeout_action"`
	ProcessMaxAttempts  int32              `json:"process_max_attempts"`
	ProcessRetryBackoff *string            `json:"process_retry_backoff"`
}

func (q *Queries) GetRunWithProcess(ctx context.Context, arg GetRunWithProcessParams) (GetRunWithProcessRow, error) {
	row := q.db.QueryRow(ctx, getRunWithProcess, arg.ID, arg.WorkspaceID)
	var i GetRunWithProcessRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProcessID,
		&i.ScheduledAt,
		&i.State,
		&i.Origin,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ExitCode,
		&i.ProgressTotal,
		&i.ProgressCurrent,
		&i.Progress,
		&i.ProgressMessage,
		&i.LastHeartbeatAt,
		&i.QueueReason,
		&i.WaitingReason,
		&i.ActorType,
		&i.ActorID,
		&i.KilledByActorType,
		&i.KilledByActorID,
		&i.TriggeredByRunID,
		&i.ReplayedFromRunID,
		&i.EffectiveConfig,
		&i.Runtime,
		&i.WorkerID,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessName,
		&i.ExecutionMethod,
		&i.MethodConfig,
		&i.ExecutionTimeout,
		&i.HeartbeatTimeout,
		&i.TimeoutAction,
		&i.ProcessMaxAttempts,
		&i.ProcessRetryBackoff,
	)
	return i, err
}

const listKillRequestedRuns = `-- name: ListKillRequestedRuns :many
SELECT r.id, r.workspace_id, r.process_id, r.scheduled_at, r.state, r.origin, r.attempt, r.max_attempts, r.next_attempt_at, r.started_at, r.finished_at, r.duration_ms, r.exit_code, r.progress_total, r.progress_current, r.progress, r.progress_message, r.last_heartbeat_at, r.queue_reason, r.waiting_reason, r.actor_type, r.actor_id, r.killed_by_actor_type, r.killed_by_actor_id, r.triggered_by_run_id, r.replayed_from_run_id, r.effective_config, r.runtime, r.worker_id, r.tags, r.created_at, r.updated_at, p.execution_method, p.runtime
FROM runs r
JOIN processes p ON p.id = r.process_id
WHERE r.state = 'kill_requested'
`

type ListKillRequestedRunsRow struct {
	ID                string             `json:"id"`
	WorkspaceID       string             `json:"workspace_id"`
	ProcessID         string             `json:"process_id"`
	ScheduledAt       pgtype.Timestamptz `json:"scheduled_at"`
	State             string             `json:"state"`
	Origin            string             `json:"origin"`
	Attempt           int32              `json:"attempt"`
	MaxAttempts       int32              `json:"max_attempts"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	DurationMs        *int64             `json:"duration_ms"`
	ExitCode          *int32             `json:"exit_code"`
	ProgressTotal     *int32             `json:"progress_total"`
	ProgressCurrent   *int32             `json:"progress_current"`
	Progress          *int32             `json:"progress"`
	ProgressMessage   *string            `json:"progress_message"`
	LastHeartbeatAt   pgtype.Timestamptz `json:"last_heartbeat_at"`
	QueueReason       *string            `json:"queue_reason"`
	WaitingReason     *string            `json:"waiting_reason"`
	ActorType         *string            `json:"actor_type"`
	ActorID           *string            `json:"actor_id"`
	KilledByActorType *string            `json:"killed_by_actor_type"`
	KilledByActorID   *string            `json:"killed_by_actor_id"`
	TriggeredByRunID  *string            `json:"triggered_by_run_id"`
	ReplayedFromRunID *string            `json:"replayed_from_run_id"`
	EffectiveConfig   []byte             `json:"effective_config"`
	Runtime           *string            `json:"runtime"`
	WorkerID          *string            `json:"worker_id"`
	Tags              []string           `json:"tags"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ExecutionMethod   string             `json:"execution_method"`
	Runtime_2         string             `json:"runtime_2"`
}

func (q *Queries) ListKillRequestedRuns(ctx context.Context) ([]ListKillRequestedRunsRow, error) {
	rows, err := q.db.Query(ctx, listKillRequestedRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKillRequestedRunsRow{}
	for rows.Next() {
		var i ListKillRequestedRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProcessID,
			&i.ScheduledAt,
			&i.State,
			&i.Origin,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ExitCode,
			&i.ProgressTotal,
			&i.ProgressCurrent,
			&i.Progress,
			&i.ProgressMessage,
			&i.LastHeartbeatAt,
			&i.QueueReason,
			&i.WaitingReason,
			&i.ActorType,
			&i.ActorID,
			&i.KilledByActorType,
			&i.KilledByActorID,
			&i.TriggeredByRunID,
			&i.ReplayedFromRunID,
			&i.EffectiveConfig,
			&i.Runtime,
			&i.WorkerID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExecutionMethod,
			&i.Runtime_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningRuns = `-- name: ListRunningRuns :many
SELECT r.id, r.workspace_id, r.process_id, r.scheduled_at, r.state, r.origin, r.attempt, r.max_attempts, r.next_attempt_at, r.started_at, r.finished_at, r.duration_ms, r.exit_code, r.progress_total, r.progress_current, r.progress, r.progress_message, r.last_heartbeat_at, r.queue_reason, r.waiting_reason, r.actor_type, r.actor_id, r.killed_by_actor_type, r.killed_by_actor_id, r.triggered_by_run_id, r.replayed_from_run_id, r.effective_config, r.runtime, r.worker_id, r.tags, r.created_at, r.updated_at, p.execution_timeout, p.heartbeat_timeout, p.timeout_action, p.execution_method
FROM runs r
JOIN processes p ON p.id = r.process_id
WHERE r.state = 'running'
`

type ListRunningRunsRow struct {
	ID                string             `json:"id"`
	WorkspaceID       string             `json:"workspace_id"`
	ProcessID         string             `json:"process_id"`
	ScheduledAt       pgtype.Timestamptz `json:"scheduled_at"`
	State             string             `json:"state"`
	Origin            string             `json:"origin"`
	Attempt           int32              `json:"attempt"`
	MaxAttempts       int32              `json:"max_attempts"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	DurationMs        *int64             `json:"duration_ms"`
	ExitCode          *int32             `json:"exit_code"`
	ProgressTotal     *int32             `json:"progress_total"`
	ProgressCurrent   *int32             `json:"progress_current"`
	Progress          *int32             `json:"progress"`
	ProgressMessage   *string            `json:"progress_message"`
	LastHeartbeatAt   pgtype.Timestamptz `json:"last_heartbeat_at"`
	QueueReason       *string            `json:"queue_reason"`
	WaitingReason     *string            `json:"waiting_reason"`
	ActorType         *string            `json:"actor_type"`
	ActorID           *string            `json:"actor_id"`
	KilledByActorType *string            `json:"killed_by_actor_type"`
	KilledByActorID   *string            `json:"killed_by_actor_id"`
	TriggeredByRunID  *string            `json:"triggered_by_run_id"`
	ReplayedFromRunID *string            `json:"replayed_from_run_id"`
	EffectiveConfig   []byte             `json:"effective_config"`
	Runtime           *string            `json:"runtime"`
	WorkerID          *string            `json:"worker_id"`
	Tags              []string           `json:"tags"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ExecutionTimeout  pgtype.Interval    `json:"execution_timeout"`
	HeartbeatTimeout  pgtype.Interval    `json:"heartbeat_timeout"`
	TimeoutAction     string             `json:"timeout_action"`
	ExecutionMethod   string             `json:"execution_method"`
}

func (q *Queries) ListRunningRuns(ctx context.Context) ([]ListRunningRunsRow, error) {
	rows, err := q.db.Query(ctx, listRunningRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunningRunsRow{}
	for rows.Next() {
		var i ListRunningRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProcessID,
			&i.ScheduledAt,
			&i.State,
			&i.Origin,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ExitCode,
			&i.ProgressTotal,
			&i.ProgressCurrent,
			&i.Progress,
			&i.ProgressMessage,
			&i.LastHeartbeatAt,
			&i.QueueReason,
			&i.WaitingReason,
			&i.ActorType,
			&i.ActorID,
			&i.KilledByActorType,
			&i.KilledByActorID,
			&i.TriggeredByRunID,
			&i.ReplayedFromRunID,
			&i.EffectiveConfig,
			&i.Runtime,
			&i.WorkerID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExecutionTimeout,
			&i.HeartbeatTimeout,
			&i.TimeoutAction,
			&i.ExecutionMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT r.id, r.workspace_id, r.process_id, r.scheduled_at, r.state, r.origin, r.attempt, r.max_attempts, r.next_attempt_at, r.started_at, r.finished_at, r.duration_ms, r.exit_code, r.progress_total, r.progress_current, r.progress, r.progress_message, r.last_heartbeat_at, r.queue_reason, r.waiting_reason, r.actor_type, r.actor_id, r.killed_by_actor_type, r.killed_by_actor_id, r.triggered_by_run_id, r.replayed_from_run_id, r.effective_config, r.runtime, r.worker_id, r.tags, r.created_at, r.updated_at, p.name AS process_name
FROM runs r
JOIN processes p ON p.id = r.process_id
WHERE r.workspace_id = $1
  AND ($2 = '' OR r.process_id = $2)
  AND ($3 = '' OR r.state = $3)
  AND ($4 = '' OR r.origin = $4)
ORDER BY r.created_at DESC
LIMIT $5 OFFSET $6
`

type ListRunsParams struct {
	WorkspaceID string      `json:"workspace_id"`
	Column2     interface{} `json:"column_2"`
	Column3     interface{} `json:"column_3"`
	Column4     interface{} `json:"column_4"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type ListRunsRow struct {
	ID                string             `json:"id"`
	WorkspaceID       string             `json:"workspace_id"`
	ProcessID         string             `json:"process_id"`
	ScheduledAt       pgtype.Timestamptz `json:"scheduled_at"`
	State             string             `json:"state"`
	Origin            string             `json:"origin"`
	Attempt           int32              `json:"attempt"`
	MaxAttempts       int32              `json:"max_attempts"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	DurationMs        *int64             `json:"duration_ms"`
	ExitCode          *int32             `json:"exit_code"`
	ProgressTotal     *int32             `json:"progress_total"`
	ProgressCurrent   *int32             `json:"progress_current"`
	Progress          *int32             `json:"progress"`
	ProgressMessage   *string            `json:"progress_message"`
	LastHeartbeatAt   pgtype.Timestamptz `json:"last_heartbeat_at"`
	QueueReason       *string            `json:"queue_reason"`
	WaitingReason     *string            `json:"waiting_reason"`
	ActorType         *string            `json:"actor_type"`
	ActorID           *string            `json:"actor_id"`
	KilledByActorType *string            `json:"killed_by_actor_type"`
	KilledByActorID   *string            `json:"killed_by_actor_id"`
	TriggeredByRunID  *string            `json:"triggered_by_run_id"`
	ReplayedFromRunID *string            `json:"replayed_from_run_id"`
	EffectiveConfig   []byte             `json:"effective_config"`
	Runtime           *string            `json:"runtime"`
	WorkerID          *string            `json:"worker_id"`
	Tags              []string           `json:"tags"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ProcessName       string             `json:"process_name"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error) {
	rows, err := q.db.Query(ctx, listRuns,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsRow{}
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProcessID,
			&i.ScheduledAt,
			&i.State,
			&i.Origin,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ExitCode,
			&i.ProgressTotal,
			&i.ProgressCurrent,
			&i.Progress,
			&i.ProgressMessage,
			&i.LastHeartbeatAt,
			&i.QueueReason,
			&i.WaitingReason,
			&i.ActorType,
			&i.ActorID,
			&i.KilledByActorType,
			&i.KilledByActorID,
			&i.TriggeredByRunID,
			&i.ReplayedFromRunID,
			&i.EffectiveConfig,
			&i.Runtime,
			&i.WorkerID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingRuns = `-- name: ListUpcomingRuns :many
SELECT r.id, r.workspace_id, r.process_id, r.scheduled_at, r.state, r.origin, r.attempt, r.max_attempts, r.next_attempt_at, r.started_at, r.finished_at, r.duration_ms, r.exit_code, r.progress_total, r.progress_current, r.progress, r.progress_message, r.last_heartbeat_at, r.queue_reason, r.waiting_reason, r.actor_type, r.actor_id, r.killed_by_actor_type, r.killed_by_actor_id, r.triggered_by_run_id, r.replayed_from_run_id, r.effective_config, r.runtime, r.worker_id, r.tags, r.created_at, r.updated_at, p.name AS process_name
FROM runs r
JOIN processes p ON p.id = r.process_id
WHERE r.workspace_id = $1 AND r.state IN ('pending', 'queued')
ORDER BY r.scheduled_at
LIMIT $2
`

type ListUpcomingRunsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
}

type ListUpcomingRunsRow struct {
	ID                string             `json:"id"`
	WorkspaceID       string             `json:"workspace_id"`
	ProcessID         string             `json:"process_id"`
	ScheduledAt       pgtype.Timestamptz `json:"scheduled_at"`
	State             string             `json:"state"`
	Origin            string             `json:"origin"`
	Attempt           int32              `json:"attempt"`
	MaxAttempts       int32              `json:"max_attempts"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	DurationMs        *int64             `json:"duration_ms"`
	ExitCode          *int32             `json:"exit_code"`
	ProgressTotal     *int32             `json:"progress_total"`
	ProgressCurrent   *int32             `json:"progress_current"`
	Progress          *int32             `json:"progress"`
	ProgressMessage   *string            `json:"progress_message"`
	LastHeartbeatAt   pgtype.Timestamptz `json:"last_heartbeat_at"`
	QueueReason       *string            `json:"queue_reason"`
	WaitingReason     *string            `json:"waiting_reason"`
	ActorType         *string            `json:"actor_type"`
	ActorID           *string            `json:"actor_id"`
	KilledByActorType *string            `json:"killed_by_actor_type"`
	KilledByActorID   *string            `json:"killed_by_actor_id"`
	TriggeredByRunID  *string            `json:"triggered_by_run_id"`
	ReplayedFromRunID *string            `json:"replayed_from_run_id"`
	EffectiveConfig   []byte             `json:"effective_config"`
	Runtime           *string            `json:"runtime"`
	WorkerID          *string            `json:"worker_id"`
	Tags              []string           `json:"tags"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ProcessName       string             `json:"process_name"`
}

func (q *Queries) ListUpcomingRuns(ctx context.Context, arg ListUpcomingRunsParams) ([]ListUpcomingRunsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingRuns, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingRunsRow{}
	for rows.Next() {
		var i ListUpcomingRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProcessID,
			&i.ScheduledAt,
			&i.State,
			&i.Origin,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ExitCode,
			&i.ProgressTotal,
			&i.ProgressCurrent,
			&i.Progress,
			&i.ProgressMessage,
			&i.LastHeartbeatAt,
			&i.QueueReason,
			&i.WaitingReason,
			&i.ActorType,
			&i.ActorID,
			&i.KilledByActorType,
			&i.KilledByActorID,
			&i.TriggeredByRunID,
			&i.ReplayedFromRunID,
			&i.EffectiveConfig,
			&i.Runtime,
			&i.WorkerID,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runExists = `-- name: RunExists :one
SELECT EXISTS(
    SELECT 1 FROM runs
    WHERE process_id = $1 AND scheduled_at = $2 AND origin = $3
)
`

type RunExistsParams struct {
	ProcessID   string             `json:"process_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	Origin      string             `json:"origin"`
}

func (q *Queries) RunExists(ctx context.Context, arg RunExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, runExists, arg.ProcessID, arg.ScheduledAt, arg.Origin)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const snapshotRunConfig = `-- name: SnapshotRunConfig :exec
UPDATE runs SET effective_config = $2, updated_at = now() WHERE id = $1
`

type SnapshotRunConfigParams struct {
	ID              string `json:"id"`
	EffectiveConfig []byte `json:"effective_config"`
}

func (q *Queries) SnapshotRunConfig(ctx context.Context, arg SnapshotRunConfigParams) error {
	_, err := q.db.Exec(ctx, snapshotRunConfig, arg.ID, arg.EffectiveConfig)
	return err
}

const updateRunProgress = `-- name: UpdateRunProgress :exec
UPDATE runs SET
    progress_total = $2,
    progress_current = $3,
    progress = $4,
    progress_message = $5,
    last_heartbeat_at = now(),
    updated_at = now()
WHERE id = $1
`

type UpdateRunProgressParams struct {
	ID              string  `json:"id"`
	ProgressTotal   *int32  `json:"progress_total"`
	ProgressCurrent *int32  `json:"progress_current"`
	Progress        *int32  `json:"progress"`
	ProgressMessage *string `json:"progress_message"`
}

func (q *Queries) UpdateRunProgress(ctx context.Context, arg UpdateRunProgressParams) error {
	_, err := q.db.Exec(ctx, updateRunProgress,
		arg.ID,
		arg.ProgressTotal,
		arg.ProgressCurrent,
		arg.Progress,
		arg.ProgressMessage,
	)
	return err
}

const updateRunState = `-- name: UpdateRunState :exec
UPDATE runs SET
    state = $2,
    started_at = COALESCE($3, started_at),
    finished_at = COALESCE($4, finished_at),
    duration_ms = COALESCE($5, duration_ms),
    exit_code = COALESCE($6, exit_code),
    attempt = COALESCE($7, attempt),
    next_attempt_at = $8,
    queue_reason = $9,
    waiting_reason = $10,
    killed_by_actor_type = COALESCE($11, killed_by_actor_type),
    killed_by_actor_id = COALESCE($12, killed_by_actor_id),
    worker_id = COALESCE($13, worker_id),
    updated_at = now()
WHERE id = $1
`

type UpdateRunStateParams struct {
	ID                string             `json:"id"`
	State             string             `json:"state"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	DurationMs        *int64             `json:"duration_ms"`
	ExitCode          *int32             `json:"exit_code"`
	Attempt           *int32             `json:"attempt"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	QueueReason       *string            `json:"queue_reason"`
	WaitingReason     *string            `json:"waiting_reason"`
	KilledByActorType *string            `json:"killed_by_actor_type"`
	KilledByActorID   *string            `json:"killed_by_actor_id"`
	WorkerID          *string            `json:"worker_id"`
}

func (q *Queries) UpdateRunState(ctx context.Context, arg UpdateRunStateParams) error {
	_, err := q.db.Exec(ctx, updateRunState,
		arg.ID,
		arg.State,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.ExitCode,
		arg.Attempt,
		arg.NextAttemptAt,
		arg.QueueReason,
		arg.WaitingReason,
		arg.KilledByActorType,
		arg.KilledByActorID,
		arg.WorkerID,
	)
	return err
}
