// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSecret = `-- name: CreateSecret :one
INSERT INTO workspace_secrets (id, workspace_id, name, value_enc)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, created_at, updated_at
`

type CreateSecretParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
	ValueEnc    []byte `json:"value_enc"`
}

type CreateSecretRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (CreateSecretRow, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ValueEnc,
	)
	var i CreateSecretRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM workspace_secrets WHERE workspace_id = $1 AND name = $2
`

type DeleteSecretParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecret, arg.WorkspaceID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSecret = `-- name: GetSecret :one
SELECT id, workspace_id, name, value_enc, created_at, updated_at FROM workspace_secrets WHERE workspace_id = $1 AND name = $2
`

type GetSecretParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetSecret(ctx context.Context, arg GetSecretParams) (WorkspaceSecret, error) {
	row := q.db.QueryRow(ctx, getSecret, arg.WorkspaceID, arg.Name)
	var i WorkspaceSecret
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ValueEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecretsByWorkspace = `-- name: ListSecretsByWorkspace :many
SELECT id, workspace_id, name, created_at, updated_at
FROM workspace_secrets WHERE workspace_id = $1 ORDER BY name
`

type ListSecretsByWorkspaceRow struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSecretsByWorkspace(ctx context.Context, workspaceID string) ([]ListSecretsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listSecretsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsByWorkspaceRow{}
	for rows.Next() {
		var i ListSecretsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :exec
UPDATE workspace_secrets SET value_enc = $3, updated_at = now()
WHERE workspace_id = $1 AND name = $2
`

type UpdateSecretParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
	ValueEnc    []byte `json:"value_enc"`
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) error {
	_, err := q.db.Exec(ctx, updateSecret, arg.WorkspaceID, arg.Name, arg.ValueEnc)
	return err
}
