// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, auth_provider, password_hash, email_verified, active_workspace_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, name, auth_provider, password_hash, email_verified, active_workspace_id, last_login_at, created_at, updated_at, is_platform_admin
`

type CreateUserParams struct {
	ID                string  `json:"id"`
	Email             string  `json:"email"`
	Name              string  `json:"name"`
	AuthProvider      string  `json:"auth_provider"`
	PasswordHash      *string `json:"password_hash"`
	EmailVerified     bool    `json:"email_verified"`
	ActiveWorkspaceID *string `json:"active_workspace_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.AuthProvider,
		arg.PasswordHash,
		arg.EmailVerified,
		arg.ActiveWorkspaceID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AuthProvider,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ActiveWorkspaceID,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlatformAdmin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, auth_provider, password_hash, email_verified, active_workspace_id, last_login_at, created_at, updated_at, is_platform_admin FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AuthProvider,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ActiveWorkspaceID,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlatformAdmin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, auth_provider, password_hash, email_verified, active_workspace_id, last_login_at, created_at, updated_at, is_platform_admin FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AuthProvider,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.ActiveWorkspaceID,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlatformAdmin,
	)
	return i, err
}

const setActiveWorkspace = `-- name: SetActiveWorkspace :exec
UPDATE users SET active_workspace_id = $2, updated_at = now() WHERE id = $1
`

type SetActiveWorkspaceParams struct {
	ID                string  `json:"id"`
	ActiveWorkspaceID *string `json:"active_workspace_id"`
}

func (q *Queries) SetActiveWorkspace(ctx context.Context, arg SetActiveWorkspaceParams) error {
	_, err := q.db.Exec(ctx, setActiveWorkspace, arg.ID, arg.ActiveWorkspaceID)
	return err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = true, updated_at = now() WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           string  `json:"id"`
	PasswordHash *string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
