// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"
)

const createWebhookSubscription = `-- name: CreateWebhookSubscription :one
INSERT INTO webhook_subscriptions (id, workspace_id, url, secret, event_types)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, url, secret, event_types, enabled, consecutive_failures, auto_disabled, last_delivery_at, last_failure_at, created_at, updated_at
`

type CreateWebhookSubscriptionParams struct {
	ID          string   `json:"id"`
	WorkspaceID string   `json:"workspace_id"`
	Url         string   `json:"url"`
	Secret      string   `json:"secret"`
	EventTypes  []string `json:"event_types"`
}

func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, createWebhookSubscription,
		arg.ID,
		arg.WorkspaceID,
		arg.Url,
		arg.Secret,
		arg.EventTypes,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Url,
		&i.Secret,
		&i.EventTypes,
		&i.Enabled,
		&i.ConsecutiveFailures,
		&i.AutoDisabled,
		&i.LastDeliveryAt,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookSubscription = `-- name: DeleteWebhookSubscription :execrows
DELETE FROM webhook_subscriptions WHERE id = $1 AND workspace_id = $2
`

type DeleteWebhookSubscriptionParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteWebhookSubscription(ctx context.Context, arg DeleteWebhookSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookSubscription, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWebhookSubscription = `-- name: GetWebhookSubscription :one
SELECT id, workspace_id, url, secret, event_types, enabled, consecutive_failures, auto_disabled, last_delivery_at, last_failure_at, created_at, updated_at FROM webhook_subscriptions WHERE id = $1 AND workspace_id = $2
`

type GetWebhookSubscriptionParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetWebhookSubscription(ctx context.Context, arg GetWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, getWebhookSubscription, arg.ID, arg.WorkspaceID)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Url,
		&i.Secret,
		&i.EventTypes,
		&i.Enabled,
		&i.ConsecutiveFailures,
		&i.AutoDisabled,
		&i.LastDeliveryAt,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementWebhookFailures = `-- name: IncrementWebhookFailures :exec
UPDATE webhook_subscriptions SET
    consecutive_failures = consecutive_failures + 1,
    last_failure_at = now(),
    auto_disabled = CASE WHEN consecutive_failures + 1 >= 20 THEN true ELSE false END,
    enabled = CASE WHEN consecutive_failures + 1 >= 20 THEN false ELSE enabled END,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementWebhookFailures(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementWebhookFailures, id)
	return err
}

const listActiveWebhooksForEvent = `-- name: ListActiveWebhooksForEvent :many
SELECT id, workspace_id, url, secret, event_types, enabled, consecutive_failures, auto_disabled, last_delivery_at, last_failure_at, created_at, updated_at FROM webhook_subscriptions
WHERE workspace_id = $1 AND enabled = true AND auto_disabled = false
`

func (q *Queries) ListActiveWebhooksForEvent(ctx context.Context, workspaceID string) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooksForEvent, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Url,
			&i.Secret,
			&i.EventTypes,
			&i.Enabled,
			&i.ConsecutiveFailures,
			&i.AutoDisabled,
			&i.LastDeliveryAt,
			&i.LastFailureAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptionsByWorkspace = `-- name: ListWebhookSubscriptionsByWorkspace :many
SELECT id, workspace_id, url, secret, event_types, enabled, consecutive_failures, auto_disabled, last_delivery_at, last_failure_at, created_at, updated_at FROM webhook_subscriptions WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) ListWebhookSubscriptionsByWorkspace(ctx context.Context, workspaceID string) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Url,
			&i.Secret,
			&i.EventTypes,
			&i.Enabled,
			&i.ConsecutiveFailures,
			&i.AutoDisabled,
			&i.LastDeliveryAt,
			&i.LastFailureAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetWebhookFailures = `-- name: ResetWebhookFailures :exec
UPDATE webhook_subscriptions SET
    consecutive_failures = 0,
    last_delivery_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ResetWebhookFailures(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, resetWebhookFailures, id)
	return err
}

const setWebhookEnabled = `-- name: SetWebhookEnabled :exec
UPDATE webhook_subscriptions SET enabled = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2
`

type SetWebhookEnabledParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) SetWebhookEnabled(ctx context.Context, arg SetWebhookEnabledParams) error {
	_, err := q.db.Exec(ctx, setWebhookEnabled, arg.ID, arg.WorkspaceID, arg.Enabled)
	return err
}

const updateWebhookSubscription = `-- name: UpdateWebhookSubscription :one
UPDATE webhook_subscriptions SET
    url = $3,
    event_types = $4,
    updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, url, secret, event_types, enabled, consecutive_failures, auto_disabled, last_delivery_at, last_failure_at, created_at, updated_at
`

type UpdateWebhookSubscriptionParams struct {
	ID          string   `json:"id"`
	WorkspaceID string   `json:"workspace_id"`
	Url         string   `json:"url"`
	EventTypes  []string `json:"event_types"`
}

func (q *Queries) UpdateWebhookSubscription(ctx context.Context, arg UpdateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, updateWebhookSubscription,
		arg.ID,
		arg.WorkspaceID,
		arg.Url,
		arg.EventTypes,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Url,
		&i.Secret,
		&i.EventTypes,
		&i.Enabled,
		&i.ConsecutiveFailures,
		&i.AutoDisabled,
		&i.LastDeliveryAt,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
