// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRunningByWorker = `-- name: CountRunningByWorker :one
SELECT count(*) FROM runs WHERE worker_id = $1 AND state = 'running'
`

func (q *Queries) CountRunningByWorker(ctx context.Context, workerID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningByWorker, workerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (id, workspace_id, name, credential_hash, labels, max_concurrency)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, name, credential_hash, labels, capabilities, max_concurrency, version, enabled, status, last_heartbeat_at, consecutive_failures, consecutive_healthy, created_at, updated_at, enrollment_token_hash, enrollment_token_expires_at
`

type CreateWorkerParams struct {
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	Name           string `json:"name"`
	CredentialHash string `json:"credential_hash"`
	Labels         []byte `json:"labels"`
	MaxConcurrency int32  `json:"max_concurrency"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createWorker,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.CredentialHash,
		arg.Labels,
		arg.MaxConcurrency,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CredentialHash,
		&i.Labels,
		&i.Capabilities,
		&i.MaxConcurrency,
		&i.Version,
		&i.Enabled,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.ConsecutiveFailures,
		&i.ConsecutiveHealthy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollmentTokenHash,
		&i.EnrollmentTokenExpiresAt,
	)
	return i, err
}

const deleteWorker = `-- name: DeleteWorker :execrows
DELETE FROM workers WHERE id = $1 AND workspace_id = $2
`

type DeleteWorkerParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteWorker(ctx context.Context, arg DeleteWorkerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorker, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorker = `-- name: GetWorker :one
SELECT id, workspace_id, name, credential_hash, labels, capabilities, max_concurrency, version, enabled, status, last_heartbeat_at, consecutive_failures, consecutive_healthy, created_at, updated_at, enrollment_token_hash, enrollment_token_expires_at FROM workers WHERE id = $1 AND workspace_id = $2
`

type GetWorkerParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetWorker(ctx context.Context, arg GetWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorker, arg.ID, arg.WorkspaceID)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CredentialHash,
		&i.Labels,
		&i.Capabilities,
		&i.MaxConcurrency,
		&i.Version,
		&i.Enabled,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.ConsecutiveFailures,
		&i.ConsecutiveHealthy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollmentTokenHash,
		&i.EnrollmentTokenExpiresAt,
	)
	return i, err
}

const getWorkerByEnrollmentToken = `-- name: GetWorkerByEnrollmentToken :one
SELECT id, workspace_id, name, credential_hash, labels, capabilities, max_concurrency, version, enabled, status, last_heartbeat_at, consecutive_failures, consecutive_healthy, created_at, updated_at, enrollment_token_hash, enrollment_token_expires_at FROM workers
WHERE enrollment_token_hash = $1
  AND enrollment_token_expires_at > now()
`

func (q *Queries) GetWorkerByEnrollmentToken(ctx context.Context, enrollmentTokenHash *string) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByEnrollmentToken, enrollmentTokenHash)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CredentialHash,
		&i.Labels,
		&i.Capabilities,
		&i.MaxConcurrency,
		&i.Version,
		&i.Enabled,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.ConsecutiveFailures,
		&i.ConsecutiveHealthy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollmentTokenHash,
		&i.EnrollmentTokenExpiresAt,
	)
	return i, err
}

const incrementWorkerFailures = `-- name: IncrementWorkerFailures :exec
UPDATE workers SET
    consecutive_failures = consecutive_failures + 1,
    consecutive_healthy = 0,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementWorkerFailures(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementWorkerFailures, id)
	return err
}

const listOnlineWorkers = `-- name: ListOnlineWorkers :many
SELECT w.id, w.workspace_id, w.name, w.credential_hash, w.labels, w.capabilities, w.max_concurrency, w.version, w.enabled, w.status, w.last_heartbeat_at, w.consecutive_failures, w.consecutive_healthy, w.created_at, w.updated_at, w.enrollment_token_hash, w.enrollment_token_expires_at FROM workers w
WHERE w.workspace_id = $1
  AND w.enabled = true
  AND w.status = 'online'
ORDER BY (SELECT count(*) FROM runs r WHERE r.worker_id = w.id AND r.state = 'running')
LIMIT $2
`

type ListOnlineWorkersParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
}

func (q *Queries) ListOnlineWorkers(ctx context.Context, arg ListOnlineWorkersParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listOnlineWorkers, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CredentialHash,
			&i.Labels,
			&i.Capabilities,
			&i.MaxConcurrency,
			&i.Version,
			&i.Enabled,
			&i.Status,
			&i.LastHeartbeatAt,
			&i.ConsecutiveFailures,
			&i.ConsecutiveHealthy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrollmentTokenHash,
			&i.EnrollmentTokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleWorkers = `-- name: ListStaleWorkers :many
SELECT id, workspace_id, name, credential_hash, labels, capabilities, max_concurrency, version, enabled, status, last_heartbeat_at, consecutive_failures, consecutive_healthy, created_at, updated_at, enrollment_token_hash, enrollment_token_expires_at FROM workers
WHERE enabled = true
  AND status = 'online'
  AND last_heartbeat_at < now() - interval '60 seconds'
`

func (q *Queries) ListStaleWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listStaleWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CredentialHash,
			&i.Labels,
			&i.Capabilities,
			&i.MaxConcurrency,
			&i.Version,
			&i.Enabled,
			&i.Status,
			&i.LastHeartbeatAt,
			&i.ConsecutiveFailures,
			&i.ConsecutiveHealthy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrollmentTokenHash,
			&i.EnrollmentTokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersByWorkspace = `-- name: ListWorkersByWorkspace :many
SELECT id, workspace_id, name, credential_hash, labels, capabilities, max_concurrency, version, enabled, status, last_heartbeat_at, consecutive_failures, consecutive_healthy, created_at, updated_at, enrollment_token_hash, enrollment_token_expires_at FROM workers WHERE workspace_id = $1 ORDER BY name
`

func (q *Queries) ListWorkersByWorkspace(ctx context.Context, workspaceID string) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CredentialHash,
			&i.Labels,
			&i.Capabilities,
			&i.MaxConcurrency,
			&i.Version,
			&i.Enabled,
			&i.Status,
			&i.LastHeartbeatAt,
			&i.ConsecutiveFailures,
			&i.ConsecutiveHealthy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrollmentTokenHash,
			&i.EnrollmentTokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkerEnabled = `-- name: SetWorkerEnabled :exec
UPDATE workers SET enabled = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2
`

type SetWorkerEnabledParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) SetWorkerEnabled(ctx context.Context, arg SetWorkerEnabledParams) error {
	_, err := q.db.Exec(ctx, setWorkerEnabled, arg.ID, arg.WorkspaceID, arg.Enabled)
	return err
}

const setWorkerEnrollmentToken = `-- name: SetWorkerEnrollmentToken :exec
UPDATE workers SET
    enrollment_token_hash = $2,
    enrollment_token_expires_at = $3,
    updated_at = now()
WHERE id = $1
`

type SetWorkerEnrollmentTokenParams struct {
	ID                       string             `json:"id"`
	EnrollmentTokenHash      *string            `json:"enrollment_token_hash"`
	EnrollmentTokenExpiresAt pgtype.Timestamptz `json:"enrollment_token_expires_at"`
}

func (q *Queries) SetWorkerEnrollmentToken(ctx context.Context, arg SetWorkerEnrollmentTokenParams) error {
	_, err := q.db.Exec(ctx, setWorkerEnrollmentToken, arg.ID, arg.EnrollmentTokenHash, arg.EnrollmentTokenExpiresAt)
	return err
}

const setWorkerStatus = `-- name: SetWorkerStatus :exec
UPDATE workers SET status = $2, updated_at = now() WHERE id = $1
`

type SetWorkerStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetWorkerStatus(ctx context.Context, arg SetWorkerStatusParams) error {
	_, err := q.db.Exec(ctx, setWorkerStatus, arg.ID, arg.Status)
	return err
}

const updateWorkerCredentialHash = `-- name: UpdateWorkerCredentialHash :exec
UPDATE workers SET
    credential_hash = $2,
    enrollment_token_hash = NULL,
    enrollment_token_expires_at = NULL,
    updated_at = now()
WHERE id = $1
`

type UpdateWorkerCredentialHashParams struct {
	ID             string `json:"id"`
	CredentialHash string `json:"credential_hash"`
}

func (q *Queries) UpdateWorkerCredentialHash(ctx context.Context, arg UpdateWorkerCredentialHashParams) error {
	_, err := q.db.Exec(ctx, updateWorkerCredentialHash, arg.ID, arg.CredentialHash)
	return err
}

const updateWorkerHeartbeat = `-- name: UpdateWorkerHeartbeat :exec
UPDATE workers SET
    last_heartbeat_at = now(),
    status = 'online',
    capabilities = COALESCE($2, capabilities),
    version = COALESCE($3, version),
    consecutive_failures = 0,
    consecutive_healthy = consecutive_healthy + 1,
    updated_at = now()
WHERE id = $1
`

type UpdateWorkerHeartbeatParams struct {
	ID           string  `json:"id"`
	Capabilities []byte  `json:"capabilities"`
	Version      *string `json:"version"`
}

func (q *Queries) UpdateWorkerHeartbeat(ctx context.Context, arg UpdateWorkerHeartbeatParams) error {
	_, err := q.db.Exec(ctx, updateWorkerHeartbeat, arg.ID, arg.Capabilities, arg.Version)
	return err
}

const updateWorkerLabels = `-- name: UpdateWorkerLabels :exec
UPDATE workers SET labels = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2
`

type UpdateWorkerLabelsParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Labels      []byte `json:"labels"`
}

func (q *Queries) UpdateWorkerLabels(ctx context.Context, arg UpdateWorkerLabelsParams) error {
	_, err := q.db.Exec(ctx, updateWorkerLabels, arg.ID, arg.WorkspaceID, arg.Labels)
	return err
}
