// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package db

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, slug, name, state)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, state, default_timezone, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID    string `json:"id"`
	Slug  string `json:"slug"`
	Name  string `json:"name"`
	State string `json:"state"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.State,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.State,
		&i.DefaultTimezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, slug, name, state, default_timezone, created_at, updated_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.State,
		&i.DefaultTimezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, slug, name, state, default_timezone, created_at, updated_at FROM workspaces WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.State,
		&i.DefaultTimezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces SET
    name = COALESCE($2, name),
    default_timezone = COALESCE($3, default_timezone),
    updated_at = now()
WHERE id = $1
RETURNING id, slug, name, state, default_timezone, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	ID              string  `json:"id"`
	Name            *string `json:"name"`
	DefaultTimezone *string `json:"default_timezone"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.ID, arg.Name, arg.DefaultTimezone)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.State,
		&i.DefaultTimezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceState = `-- name: UpdateWorkspaceState :exec
UPDATE workspaces SET state = $2, updated_at = now() WHERE id = $1
`

type UpdateWorkspaceStateParams struct {
	ID    string `json:"id"`
	State string `json:"state"`
}

func (q *Queries) UpdateWorkspaceState(ctx context.Context, arg UpdateWorkspaceStateParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceState, arg.ID, arg.State)
	return err
}
